import type { HelpMeta } from '@/game/console/help';

/**
 * The help facts for the travel commands (game/console/travel). Kept out of help.ts so the
 * player build, which does not register those commands (`__AUTHORING__`), does not carry their
 * text either.
 */
export const TRAVEL_HELP_META: Readonly<Record<string, HelpMeta>> = {
  levels: {
    group: 'runs',
    order: 20,
    summary: 'list every level: floor, biome, boss, which doors lead where',
    examples: ['levels'],
    detail: ['Marks the level you are in and the levels generated so far this run. The ids are what goto, level and run test --level take.'],
  },
  goto: {
    group: 'runs',
    order: 30,
    args: '<level|floor|next|prev> [--at spot]',
    summary: 'travel to a level; the run is kept',
    taints: true,
    examples: ['goto d3', 'goto 4 --at boss', 'goto next --at portal', 'goto d2b --seed 4242', 'goto prev'],
    detail: [
      'Travels through the real transition: the curtain, the arrival banner and grace, level persistence, the findability repair and the story hooks. The run is kept: phials, boons, kit, tier, gold, counters.',
      'A level not generated yet is built from the run seed exactly as the descent would build it; a level already visited keeps its world, scars and all. --seed n (or --fresh) throws the visited world away and builds it again from n (or the run seed).',
      'Floors skipped are skipped: no boon, no phial pour, no shop. skip takes the stairs properly, through the Sanctum. next, prev and a floor number pick the door this run took on that floor, else the first door; name the other door by id (d2b, d3b).',
      '--at spawn|portal|boss|camp|waystone|valve|key moves you to that spot on arrival. Works with the Sanctum open and after a death; on the title or a finished run it says what to start.',
    ],
  },
  skip: {
    group: 'runs',
    order: 40,
    args: '[--no-sanctum] [--door id]',
    summary: 'finish this floor the way the exit portal does',
    taints: true,
    examples: ['skip', 'skip --no-sanctum', 'skip --no-sanctum --door d3b'],
    detail: [
      'Takes the exit portal: the Sanctum opens (boon draft, shop, the door choice and the return phial pour) and you descend when you close it. --no-sanctum strikes the first boon on offer and takes the named door (else the first) for you, through the same Sanctum code.',
      'On the Kiln Heart there is no stair: skip ends the descent as a victory (the same as win).',
    ],
  },
  sanctum: {
    group: 'runs',
    order: 50,
    args: '[floor]',
    summary: 'open the Sanctum as if a floor was just finished',
    taints: true,
    examples: ['sanctum', 'sanctum 2'],
    detail: ['With a floor number, goes to that floor first (the way goto does), then opens the Sanctum. The Sanctum is the real one: pick a boon and a door and you descend.'],
  },
  portal: {
    group: 'runs',
    order: 60,
    summary: "teleport beside this floor's exit portal",
    taints: true,
    examples: ['portal'],
    detail: ['Stops short of the gate, on footing with headroom. Walk in with the key to wake it, or use key first.'],
  },
  boss: {
    group: 'runs',
    order: 70,
    args: '[kill]',
    summary: "teleport to the floor's guardian; boss kill fells it",
    taints: true,
    examples: ['boss', 'boss kill'],
    detail: ['boss kill takes the guardian down through the real death path: its drops, its toast, and on the Kiln Heart the Colossus starts the escape up the flue.'],
  },
  key: {
    group: 'runs',
    order: 80,
    summary: "take the golden key (D1's brass bell)",
    taints: true,
    examples: ['key'],
    detail: ['Collects the floor\'s key through the code Pickups uses, so the portal wakes, the compass points at it and the objective changes. On D1 the lower gate also wants the engine\'s bell to ring and the grate open: skip goes around all of it.'],
  },
  waystone: {
    group: 'runs',
    order: 90,
    args: '[tp|light] [n]',
    summary: 'go to, or light, a waystone (the respawn anchor)',
    taints: true,
    examples: ['waystone', 'waystone light', 'waystone tp 2'],
    detail: ['tp (the default) goes to waystone n, else the nearest unlit one. light lights it through the real ignition: the gong, the embers, full vitals, and the respawn anchor moves there.'],
  },
  phials: {
    group: 'runs',
    order: 100,
    args: '[0-3]',
    summary: 'show or set the return phials',
    taints: true,
    examples: ['phials', 'phials 1', 'phials 0'],
    detail: ['A death spends one; with none left a death ends the run. Setting them taints the run; showing them does not.'],
  },
  boon: {
    group: 'runs',
    order: 110,
    args: '[id]',
    summary: 'list the Sanctum boons, or strike one',
    taints: true,
    examples: ['boon', 'boon ironhide', 'boon vitality'],
    detail: ['Striking goes through the Sanctum\'s own code (the flag on the alchemist, the chime, the telemetry), outside the once-per-floor draft. Matron Ash stays quiet: she is not in the room.'],
  },
  kit: {
    group: 'runs',
    order: 120,
    args: '[id]',
    summary: "show or switch the starting kit's hand",
    taints: true,
    examples: ['kit', 'kit storm'],
    detail: ["Switching resets both wands, the satchel and the flask belt to that kit's starting hand (cards found this run are dropped) and names the kit in the ledger. Kits you have not unlocked are fine here: a test run unlocks nothing."],
  },
  fighter: {
    group: 'runs',
    order: 125,
    args: '[id|none|charge|refill]',
    summary: 'list the fighters, equip one, or top up the ultimate',
    taints: true,
    examples: ['fighter', 'fighter ilyra-voss', 'fighter none', 'fighter charge', 'fighter refill'],
    detail: [
      'A fighter is who you descend as: a look, a passive, a tactical ability on Z and an ultimate on T (docs/FIGHTERS.md). Listing never taints. Equipping, charging or refilling does when a real run is in progress; in the Sandbox nothing is tainted.',
      'charge adds a share of the ultimate bar (default all of it); refill clears the tactical cooldown and fills the bar. none returns to the classic Alchemist.',
    ],
  },
  tier: {
    group: 'runs',
    order: 130,
    args: '[1-4]',
    summary: 'show or set the difficulty tier',
    taints: true,
    examples: ['tier', 'tier 4'],
    detail: ['Foes already placed on generated floors keep their stats; floors generated from now on, and damage and death penalties, follow the new tier. The remembered tier on the title is not touched.'],
  },
  mutator: {
    group: 'runs',
    order: 135,
    args: '[list|add|remove|set|clear] [id]',
    summary: 'list the complications, or put them in force',
    taints: true,
    examples: ['mutator', 'mutator add wet-floors', 'mutator set low-gravity,tinderbox', 'mutator clear'],
    detail: [
      "Complications are the standing regulations a descent runs under (the title's Complications fold). Listing never taints; changing the set does, because a complication put on by hand is not the descent the player chose.",
      "The dials follow at once: foes spawned from now on, gravity, the alchemist's damage and health, healing, bounties, fuel and light. The puddles and vents are laid when a floor is built, so a floor already built keeps what it had; goto a new floor to see them.",
    ],
  },
  seed: {
    group: 'runs',
    order: 140,
    summary: 'show the run seed and every level seed',
    examples: ['seed'],
    detail: [
      "A run's seed is fixed when it starts. To start over on a seed: run new --seed n. To rebuild one floor from a seed inside this run: goto <level> --seed n.",
    ],
  },
  win: {
    group: 'runs',
    order: 150,
    summary: 'end the run as a victory (no escape, no ending plates)',
    taints: true,
    examples: ['win'],
    detail: ['Ends the run through RunDirector the way the top of the flue does. The ledger shows it as a practice descent and records nothing. The saved expedition is retired as in a real victory only when the run was never tainted; a test run leaves an older checkpoint alone.'],
  },
  lose: {
    group: 'runs',
    order: 160,
    summary: 'end the run as a fall',
    taints: true,
    examples: ['lose'],
    detail: ['Empties the phials and kills the alchemist through the real death path, so the death screen, the corpse and the ledger all run. Turns god mode off first if it was on.'],
  },
  respawn: {
    group: 'player',
    summary: 'get up after a death (the R key)',
    examples: ['respawn'],
    detail: ['Does what the death screen\'s button does: back at the last lit waystone or the level spawn. No phial is spent (the death already spent it). A finished run has no respawn; its ledger offers another descent.'],
  },
  camp: {
    group: 'story',
    summary: "teleport to Pell's camp on this floor",
    taints: true,
    examples: ['camp'],
    detail: ['Then press E to talk. The floor\'s camp exists on every floor; the dialogue, the gift and what he remembers are the real ones. A test run hears them from a scratch memory: nothing it hears is marked heard for the player.'],
  },
  echo: {
    group: 'story',
    summary: "teleport to this floor's resonant valve (the memory echo)",
    taints: true,
    examples: ['echo'],
    detail: ['Then press E at the valve to turn it. The echo plays as it would; in a test run it is not marked heard.'],
  },
  seq: {
    group: 'console',
    args: '<command; command; ...>',
    summary: 'run several commands in order, stopping at the first failure',
    examples: ['seq goto d3; key; portal', 'seq goto d2b --seed 7; boss kill'],
    detail: ['Quote a semicolon you need inside an argument. Each command waits for the one before it, so a travel finishes before the next line runs.'],
  },
};
