// GENERATED by scripts/gen-tuning-ranges.mjs — do not edit.
// Source: src/config/tuningRanges.ts (+ ui/Inspector paramSliderSpec, config/gen).
// 173 of 199 tuning paths carry declared bounds; a strict
// (hosted) room refuses the rest rather than clamping them silently.

export interface TuningRange {
  min: number;
  max: number;
  step?: number;
}

export const TUNING_RANGES: Record<string, TuningRange> = {
  "gen.caveScale": {
    "min": 0.6,
    "max": 2.2,
    "step": 0.05
  },
  "gen.notchPasses": {
    "min": 0,
    "max": 6,
    "step": 1
  },
  "gen.surfacePitDepth": {
    "min": 1,
    "max": 14,
    "step": 1
  },
  "gen.surfacePitWidth": {
    "min": 0,
    "max": 24,
    "step": 1
  },
  "global.ambient": {
    "min": 0.02,
    "max": 0.5,
    "step": 0.02
  },
  "global.maxBrightness": {
    "min": 1,
    "max": 10,
    "step": 0.5
  },
  "global.simSpeed": {
    "min": 0,
    "max": 2,
    "step": 0.1
  },
  "materials.1.densityWeight": {
    "min": 0,
    "max": 1,
    "step": 0.05
  },
  "materials.1.friction": {
    "min": 0,
    "max": 1,
    "step": 0.05
  },
  "materials.10.insulationRating": {
    "min": 0,
    "max": 1,
    "step": 0.05
  },
  "materials.11.bloomWeight": {
    "min": 0,
    "max": 1,
    "step": 0.05
  },
  "materials.11.flowRate": {
    "min": 0,
    "max": 1,
    "step": 0.05
  },
  "materials.11.meltRange": {
    "min": 0,
    "max": 1,
    "step": 0.05
  },
  "materials.13.conductivity": {
    "min": 0,
    "max": 1,
    "step": 0.05
  },
  "materials.14.bloomWeight": {
    "min": 0,
    "max": 1,
    "step": 0.05
  },
  "materials.14.dispersion": {
    "min": 0,
    "max": 0.5,
    "step": 0.005
  },
  "materials.14.floatSpeed": {
    "min": 0,
    "max": 1,
    "step": 0.05
  },
  "materials.15.flammability": {
    "min": 0,
    "max": 1,
    "step": 0.05
  },
  "materials.16.evaporationSpeed": {
    "min": 0,
    "max": 0.1,
    "step": 0.001
  },
  "materials.16.flowRate": {
    "min": 0,
    "max": 1,
    "step": 0.05
  },
  "materials.17.bloomWeight": {
    "min": 0,
    "max": 1,
    "step": 0.05
  },
  "materials.17.densityWeight": {
    "min": 0,
    "max": 1,
    "step": 0.05
  },
  "materials.17.friction": {
    "min": 0,
    "max": 1,
    "step": 0.05
  },
  "materials.18.coagulation": {
    "min": 0,
    "max": 0.02,
    "step": 0.001
  },
  "materials.18.conductivity": {
    "min": 0,
    "max": 1,
    "step": 0.05
  },
  "materials.18.flowRate": {
    "min": 0,
    "max": 1,
    "step": 0.05
  },
  "materials.19.bloomWeight": {
    "min": 0,
    "max": 1,
    "step": 0.05
  },
  "materials.19.flowRate": {
    "min": 0,
    "max": 1,
    "step": 0.05
  },
  "materials.2.flowRate": {
    "min": 0,
    "max": 1,
    "step": 0.05
  },
  "materials.2.poolingFactor": {
    "min": 0,
    "max": 1,
    "step": 0.05
  },
  "materials.20.bloomWeight": {
    "min": 0,
    "max": 1,
    "step": 0.05
  },
  "materials.20.fallChance": {
    "min": 0,
    "max": 1,
    "step": 0.05
  },
  "materials.20.igniteChance": {
    "min": 0,
    "max": 0.2,
    "step": 0.005
  },
  "materials.21.bloomWeight": {
    "min": 0,
    "max": 1,
    "step": 0.05
  },
  "materials.21.flowRate": {
    "min": 0,
    "max": 1,
    "step": 0.05
  },
  "materials.22.bloomWeight": {
    "min": 0,
    "max": 1,
    "step": 0.05
  },
  "materials.22.flowRate": {
    "min": 0,
    "max": 1,
    "step": 0.05
  },
  "materials.23.bloomWeight": {
    "min": 0,
    "max": 1,
    "step": 0.05
  },
  "materials.23.flowRate": {
    "min": 0,
    "max": 1,
    "step": 0.05
  },
  "materials.24.bloomWeight": {
    "min": 0,
    "max": 1,
    "step": 0.05
  },
  "materials.24.flammability": {
    "min": 0,
    "max": 1,
    "step": 0.05
  },
  "materials.24.flowRate": {
    "min": 0,
    "max": 1,
    "step": 0.05
  },
  "materials.25.bloomWeight": {
    "min": 0,
    "max": 1,
    "step": 0.05
  },
  "materials.25.evaporationSpeed": {
    "min": 0,
    "max": 0.1,
    "step": 0.001
  },
  "materials.25.flowRate": {
    "min": 0,
    "max": 1,
    "step": 0.05
  },
  "materials.26.bloomWeight": {
    "min": 0,
    "max": 1,
    "step": 0.05
  },
  "materials.26.flowRate": {
    "min": 0,
    "max": 1,
    "step": 0.05
  },
  "materials.27.friction": {
    "min": 0,
    "max": 1,
    "step": 0.05
  },
  "materials.28.burnDuration": {
    "min": 5,
    "max": 360,
    "step": 5
  },
  "materials.28.friction": {
    "min": 0,
    "max": 1,
    "step": 0.05
  },
  "materials.28.igniteChance": {
    "min": 0,
    "max": 0.2,
    "step": 0.005
  },
  "materials.29.bloomWeight": {
    "min": 0,
    "max": 1,
    "step": 0.05
  },
  "materials.30.bloomWeight": {
    "min": 0,
    "max": 1,
    "step": 0.05
  },
  "materials.30.flammability": {
    "min": 0,
    "max": 1,
    "step": 0.05
  },
  "materials.32.friction": {
    "min": 0,
    "max": 1,
    "step": 0.05
  },
  "materials.33.bloomWeight": {
    "min": 0,
    "max": 1,
    "step": 0.05
  },
  "materials.33.flammability": {
    "min": 0,
    "max": 1,
    "step": 0.05
  },
  "materials.34.bloomWeight": {
    "min": 0,
    "max": 1,
    "step": 0.05
  },
  "materials.34.flammability": {
    "min": 0,
    "max": 1,
    "step": 0.05
  },
  "materials.35.bloomWeight": {
    "min": 0,
    "max": 1,
    "step": 0.05
  },
  "materials.35.densityWeight": {
    "min": 0,
    "max": 1,
    "step": 0.05
  },
  "materials.35.friction": {
    "min": 0,
    "max": 1,
    "step": 0.05
  },
  "materials.36.bloomWeight": {
    "min": 0,
    "max": 1,
    "step": 0.05
  },
  "materials.37.flammability": {
    "min": 0,
    "max": 1,
    "step": 0.05
  },
  "materials.38.bloomWeight": {
    "min": 0,
    "max": 1,
    "step": 0.05
  },
  "materials.38.dispersion": {
    "min": 0,
    "max": 0.5,
    "step": 0.005
  },
  "materials.38.floatSpeed": {
    "min": 0,
    "max": 1,
    "step": 0.05
  },
  "materials.4.carbonSmokeGen": {
    "min": 0,
    "max": 1,
    "step": 0.05
  },
  "materials.4.flammability": {
    "min": 0,
    "max": 1,
    "step": 0.05
  },
  "materials.5.bloomWeight": {
    "min": 0,
    "max": 1,
    "step": 0.05
  },
  "materials.5.particleLife": {
    "min": 5,
    "max": 360,
    "step": 5
  },
  "materials.5.upwardSpread": {
    "min": 0,
    "max": 1,
    "step": 0.05
  },
  "materials.6.burnDuration": {
    "min": 5,
    "max": 360,
    "step": 5
  },
  "materials.6.flowRate": {
    "min": 0,
    "max": 1,
    "step": 0.05
  },
  "materials.6.igniteChance": {
    "min": 0,
    "max": 0.2,
    "step": 0.005
  },
  "materials.7.bloomWeight": {
    "min": 0,
    "max": 1,
    "step": 0.05
  },
  "materials.7.corrosiveSpeed": {
    "min": 0,
    "max": 1,
    "step": 0.05
  },
  "materials.7.flowRate": {
    "min": 0,
    "max": 1,
    "step": 0.05
  },
  "materials.8.blastRadius": {
    "min": 5,
    "max": 100,
    "step": 1
  },
  "materials.8.clumpMaxAnisotropy": {
    "min": 1,
    "max": 8,
    "step": 0.1
  },
  "materials.8.clumpMinMass": {
    "min": 1,
    "max": 128,
    "step": 1
  },
  "materials.8.clumpMinSpan": {
    "min": 1,
    "max": 16,
    "step": 1
  },
  "materials.8.clumpScanRadius": {
    "min": 1,
    "max": 8,
    "step": 1
  },
  "materials.8.friction": {
    "min": 0,
    "max": 1,
    "step": 0.05
  },
  "materials.8.fuseCadence": {
    "min": 1,
    "max": 12,
    "step": 1
  },
  "materials.9.bloomWeight": {
    "min": 0,
    "max": 1,
    "step": 0.05
  },
  "player.airDrag": {
    "min": 0,
    "max": 1,
    "step": 0.05
  },
  "player.airGlideSpeed": {
    "min": 0,
    "max": 4,
    "step": 0.1
  },
  "player.airStopDecay": {
    "min": 0,
    "max": 1,
    "step": 0.02
  },
  "player.groundStopDecay": {
    "min": 0,
    "max": 1,
    "step": 0.02
  },
  "player.groundStopSnap": {
    "min": 0,
    "max": 0.6,
    "step": 0.01
  },
  "player.jumpCut": {
    "min": 0,
    "max": 0.6,
    "step": 0.01
  },
  "player.jumpHoldWindow": {
    "min": 0,
    "max": 30,
    "step": 1
  },
  "player.kickArc": {
    "min": 0,
    "max": 1,
    "step": 0.05
  },
  "player.kickCooldown": {
    "min": 0,
    "max": 100,
    "step": 1
  },
  "player.kickDamage": {
    "min": 0,
    "max": 100,
    "step": 1
  },
  "player.kickImpulse": {
    "min": 0,
    "max": 100,
    "step": 1
  },
  "player.kickRange": {
    "min": 0,
    "max": 100,
    "step": 1
  },
  "player.kickSelfRecoil": {
    "min": 0,
    "max": 3,
    "step": 0.05
  },
  "player.levitDrag": {
    "min": 0,
    "max": 1,
    "step": 0.02
  },
  "player.levitHorizControl": {
    "min": 0,
    "max": 1,
    "step": 0.02
  },
  "player.levitRampFrames": {
    "min": 0,
    "max": 48,
    "step": 1
  },
  "player.levitThrust0": {
    "min": 0,
    "max": 1,
    "step": 0.05
  },
  "player.levitThrustGain": {
    "min": 0,
    "max": 1,
    "step": 0.05
  },
  "player.maxRunCap": {
    "min": 1,
    "max": 8,
    "step": 0.1
  },
  "player.moveSoftStart": {
    "min": 0,
    "max": 1,
    "step": 0.02
  },
  "player.recoilBase": {
    "min": 0,
    "max": 100,
    "step": 1
  },
  "player.recoilGroundDamp": {
    "min": 0,
    "max": 1,
    "step": 0.05
  },
  "player.recoilMaxImpulse": {
    "min": 0,
    "max": 4,
    "step": 0.05
  },
  "player.recoilPerMomentum": {
    "min": 0,
    "max": 1,
    "step": 0.05
  },
  "player.vyCapUp": {
    "min": -4.6,
    "max": 1,
    "step": 0.05
  },
  "spells.blackhole.baseRadius": {
    "min": 5,
    "max": 100,
    "step": 1
  },
  "spells.blackhole.chargeRate": {
    "min": 0.05,
    "max": 2,
    "step": 0.05
  },
  "spells.blackhole.collapseLimit": {
    "min": 5,
    "max": 140,
    "step": 1
  },
  "spells.blackhole.cooldown": {
    "min": 0,
    "max": 180,
    "step": 1
  },
  "spells.blackhole.manaCost": {
    "min": 0,
    "max": 100,
    "step": 1
  },
  "spells.bolt.cooldown": {
    "min": 0,
    "max": 180,
    "step": 1
  },
  "spells.bolt.explosionRadius": {
    "min": 1,
    "max": 20,
    "step": 0.5
  },
  "spells.bolt.manaCost": {
    "min": 0,
    "max": 100,
    "step": 1
  },
  "spells.bolt.velocityForce": {
    "min": 1,
    "max": 20,
    "step": 0.5
  },
  "spells.bomb.cooldown": {
    "min": 0,
    "max": 180,
    "step": 1
  },
  "spells.bomb.explosionRadius": {
    "min": 1,
    "max": 52,
    "step": 0.5
  },
  "spells.bomb.fuseTicks": {
    "min": 5,
    "max": 120,
    "step": 1
  },
  "spells.bomb.manaCost": {
    "min": 0,
    "max": 100,
    "step": 1
  },
  "spells.bomb.velocityForce": {
    "min": 1,
    "max": 20,
    "step": 0.5
  },
  "spells.conjure.cooldown": {
    "min": 0,
    "max": 180,
    "step": 1
  },
  "spells.conjure.manaCost": {
    "min": 0,
    "max": 100,
    "step": 1
  },
  "spells.conjure.radius": {
    "min": 1,
    "max": 24,
    "step": 1
  },
  "spells.conjure.range": {
    "min": 20,
    "max": 250,
    "step": 5
  },
  "spells.dig.cooldown": {
    "min": 0,
    "max": 180,
    "step": 1
  },
  "spells.dig.manaCost": {
    "min": 0,
    "max": 100,
    "step": 1
  },
  "spells.dig.range": {
    "min": 20,
    "max": 250,
    "step": 5
  },
  "spells.emberstorm.cooldown": {
    "min": 0,
    "max": 180,
    "step": 1
  },
  "spells.emberstorm.count": {
    "min": 1,
    "max": 32,
    "step": 1
  },
  "spells.emberstorm.manaCost": {
    "min": 0,
    "max": 100,
    "step": 1
  },
  "spells.flame.cooldown": {
    "min": 0,
    "max": 180,
    "step": 1
  },
  "spells.flame.heat": {
    "min": 1,
    "max": 60,
    "step": 1
  },
  "spells.flame.manaCost": {
    "min": 0,
    "max": 100,
    "step": 1
  },
  "spells.flame.spread": {
    "min": 0,
    "max": 1,
    "step": 0.05
  },
  "spells.frostshard.cooldown": {
    "min": 0,
    "max": 180,
    "step": 1
  },
  "spells.frostshard.damage": {
    "min": 1,
    "max": 100,
    "step": 1
  },
  "spells.frostshard.freezeRadius": {
    "min": 1,
    "max": 24,
    "step": 1
  },
  "spells.frostshard.manaCost": {
    "min": 0,
    "max": 100,
    "step": 1
  },
  "spells.frostshard.velocityForce": {
    "min": 1,
    "max": 20,
    "step": 0.5
  },
  "spells.icelance.cooldown": {
    "min": 0,
    "max": 180,
    "step": 1
  },
  "spells.icelance.damage": {
    "min": 1,
    "max": 100,
    "step": 1
  },
  "spells.icelance.manaCost": {
    "min": 0,
    "max": 100,
    "step": 1
  },
  "spells.icelance.velocityForce": {
    "min": 1,
    "max": 20,
    "step": 0.5
  },
  "spells.lightning.branches": {
    "min": 0,
    "max": 6,
    "step": 1
  },
  "spells.lightning.cooldown": {
    "min": 0,
    "max": 180,
    "step": 1
  },
  "spells.lightning.damage": {
    "min": 1,
    "max": 100,
    "step": 1
  },
  "spells.lightning.manaCost": {
    "min": 0,
    "max": 100,
    "step": 1
  },
  "spells.lightning.range": {
    "min": 20,
    "max": 340,
    "step": 5
  },
  "spells.meteor.cooldown": {
    "min": 0,
    "max": 180,
    "step": 1
  },
  "spells.meteor.explosionRadius": {
    "min": 1,
    "max": 40,
    "step": 0.5
  },
  "spells.meteor.manaCost": {
    "min": 0,
    "max": 100,
    "step": 1
  },
  "spells.meteor.velocityForce": {
    "min": 1,
    "max": 20,
    "step": 0.5
  },
  "spells.scatter.cooldown": {
    "min": 0,
    "max": 180,
    "step": 1
  },
  "spells.scatter.explosionRadius": {
    "min": 1,
    "max": 20,
    "step": 0.5
  },
  "spells.scatter.manaCost": {
    "min": 0,
    "max": 100,
    "step": 1
  },
  "spells.scatter.pellets": {
    "min": 1,
    "max": 9,
    "step": 1
  },
  "spells.scatter.spread": {
    "min": 0,
    "max": 1,
    "step": 0.05
  },
  "spells.scatter.velocityForce": {
    "min": 1,
    "max": 20,
    "step": 0.5
  },
  "spells.vitriol.cooldown": {
    "min": 0,
    "max": 180,
    "step": 1
  },
  "spells.vitriol.manaCost": {
    "min": 0,
    "max": 100,
    "step": 1
  },
  "spells.vitriol.spread": {
    "min": 0,
    "max": 1,
    "step": 0.05
  },
  "spells.warp.cooldown": {
    "min": 0,
    "max": 180,
    "step": 1
  },
  "spells.warp.manaCost": {
    "min": 0,
    "max": 100,
    "step": 1
  },
  "spells.warp.velocityForce": {
    "min": 1,
    "max": 20,
    "step": 0.5
  },
  "spells.wisp.cooldown": {
    "min": 0,
    "max": 180,
    "step": 1
  },
  "spells.wisp.damage": {
    "min": 1,
    "max": 100,
    "step": 1
  },
  "spells.wisp.manaCost": {
    "min": 0,
    "max": 100,
    "step": 1
  },
  "spells.wisp.velocityForce": {
    "min": 1,
    "max": 20,
    "step": 0.5
  }
};

export function tuningRangeFor(path: string): TuningRange | null {
  return Object.prototype.hasOwnProperty.call(TUNING_RANGES, path) ? TUNING_RANGES[path] : null;
}
