// Generation table for every sampled sound effect in Breathing Works.
//
// One entry per cue id in src/content/audio/sfxCues.ts (the generator and
// tests/audio-sfx.test.ts check the two tables match). Fields:
//   p      prompt (vivid, specific, audio terminology; the palette is wet
//          slate, worn copper, brass, glass and ivory chitin)
//   d      requested duration in seconds (ElevenLabs bills 40 credits/s; min 0.5)
//   t      takes to keep (the runtime picks one at random per play)
//   i      prompt_influence (0..1; higher = more literal)
//   soft   the sound swells in (skip the late-onset rejection)
//   max    cap the trimmed one-shot at this many seconds (fade out)
// Loops and beds take their `loop` flag from sfxCues.ts.
//
// Editing a prompt changes its cache key, so the next generator run buys new
// takes for that cue only. Everything else replays from the paid cache.
//
// Plain object literals on purpose (no helper calls): the dev audition page
// imports this table through src/content/audio/sfxManifest.ts, and literals
// let the production build tree-shake every prompt out of the game bundle.

export const SFX_PROMPTS = {
  // ------------------------------------------------------------------ UI
  'ui.hover': { p: "A tiny soft brass tick, a fingertip lightly tapping a small brass switch, extremely short, dry, close-miked, subtle interface hover sound", d: 0.5, t: 3, i: 0.7, max: 0.12 },
  'ui.click': { p: "A crisp brass toggle switch click, satisfying mechanical interface click, single, very short, dry, close-miked", d: 0.5, t: 3, i: 0.7, max: 0.2 },
  'ui.back': { p: "A soft muted wooden knock followed by a small latch click, gentle interface cancel sound, very short, dry", d: 0.5, t: 2, i: 0.7, max: 0.3 },
  'ui.open': { p: "A leather-bound ledger opening: soft paper rustle and a small brass clasp unlatching, short, dry, close-miked", d: 0.8, t: 2, i: 0.65 },
  'ui.close': { p: "A leather-bound ledger closing with a soft padded thump and a brass clasp clicking shut, short, dry, close-miked", d: 0.8, t: 2, i: 0.65 },
  'ui.pause': { p: "A brass steam valve turned shut: a short soft hiss that slows and stops with a gentle mechanical clunk, quiet", d: 1, t: 2, i: 0.6 },
  'ui.resume': { p: "A brass steam valve opened: a gentle mechanical clunk and a short rising hiss of steam, quiet", d: 1, t: 2, i: 0.6 },
  'ui.toast': { p: "A single light tap on a small brass desk bell, a very short soft ding, quiet, dry", d: 0.6, t: 2, i: 0.7 },
  'ui.objective': { p: "Pneumatic tube message arriving: a short soft whoosh ending in a brass capsule thunk and a small bright bell ding", d: 1.2, t: 2, i: 0.6 },
  'ui.hint': { p: "A single parchment page turned quickly, a soft paper flick, short, close-miked, dry", d: 0.6, t: 2, i: 0.65 },
  'ui.grimoire': { p: "A quill pen scratching a quick flourish on parchment, followed by a soft warm magical glimmer chime, short", d: 1.4, t: 2, i: 0.55 },
  'ui.card.reveal': { p: "Three stiff playing cards dealt quickly in a fan onto felt, with a soft magical shimmer rising, short", d: 1.2, t: 2, i: 0.55 },
  'ui.card.choose': { p: "A single stiff card placed decisively onto a wooden table with a soft thock, followed by a short warm glassy chime", d: 1, t: 2, i: 0.6 },
  'ui.card.pick': { p: "Paper snick: a single stiff card lifted crisply off a stack, a very short paper flick, dry, close-miked", d: 0.5, t: 3, i: 0.7, max: 0.25 },
  'ui.card.slot': { p: "A brass card slotted firmly into a brass holder, a crisp metallic clack with a tiny spring snap, very short, dry", d: 0.5, t: 3, i: 0.7, max: 0.3 },
  'ui.bench': { p: "An old wooden workbench drawer slid open, brass tools and glass vials rattling softly inside, short, close-miked", d: 1.2, t: 2, i: 0.6 },
  'ui.coins': { p: "A small handful of gold coins counted onto a brass counter, bright clinks settling, short, close-miked, dry", d: 1, t: 2, i: 0.6 },
  'ui.tally': { p: "A single tiny click of a brass mechanical odometer wheel, an extremely short tick, dry", d: 0.5, t: 3, i: 0.75, max: 0.08 },
  'ui.learn': { p: "A magical discovery flourish: a rising sparkle of glass chimes and a soft warm bell, bright and short, no drums", d: 1.6, t: 2, i: 0.55 },
  'ui.curtain': { p: "A heavy velvet theatre curtain swept open with a deep soft whoosh and a low distant boom", d: 1.6, t: 2, i: 0.5, soft: true },
  'ui.phial.refill': { p: "Liquid poured into a small glass vial, a bright rising glassy fill ending in a soft clear ding", d: 1.2, t: 2, i: 0.6 },
  'ui.phial.drain': { p: "A small glass vial tapped with a thin ring, then liquid draining away with a descending hollow glug", d: 1.4, t: 2, i: 0.6 },
  'ui.run.over': { p: "A single deep, low, sombre bell toll far away in a stone hall, long dark decay", d: 2.5, t: 1, i: 0.6 },
  'ui.summary.victory': { p: "A soft warm harmonium chord swelling gently in a major key, brief, fading out, no percussion", d: 2.5, t: 1, i: 0.55, soft: true },
  'ui.summary.fallen': { p: "A soft low harmonium chord in a minor key, gentle and melancholic, slowly fading, no percussion", d: 2.5, t: 1, i: 0.55, soft: true },
  'stinger.alchemy': { p: "A single bright struck glass bell with a warm brass swell underneath, magical and satisfying, short ring", d: 1.2, t: 3, i: 0.6 },
  'stinger.phialCrack': { p: "A small glass phial cracking sharply in a hand: a bright crack, a falling glassy ring and a few tinkling shards", d: 1.2, t: 2, i: 0.6 },
  'stinger.phialFill': { p: "A glass phial filling with liquid, glugging upward in pitch, settling into a warm soft glass chime", d: 1.5, t: 2, i: 0.6 },
  'stinger.victory': { p: "A short triumphant Victorian brass fanfare sting rising to a bright held major chord with bells", d: 3.5, t: 2, i: 0.5 },
  'stinger.fallen': { p: "A short sombre descending brass sting in a minor key, ending on a cold distant glass bell", d: 3.5, t: 2, i: 0.5 },
  'stinger.shutter': { p: "An old camera shutter: a mechanical curtain click, a tiny spring whirr and a second click, very short, dry", d: 0.5, t: 2, i: 0.7 },

  // -------------------------------------------------------------- player
  'player.step.stone': { p: "A single footstep of a leather boot on wet slate stone, close-miked, dry, short", d: 0.5, t: 4, i: 0.65, max: 0.35 },
  'player.step.soft': { p: "A single footstep of a leather boot on soft sand and ash, a muffled crunch, close-miked, short", d: 0.5, t: 4, i: 0.65, max: 0.35 },
  'player.step.wet': { p: "A single footstep in a shallow puddle on stone, a small splash, close-miked, short", d: 0.5, t: 4, i: 0.65, max: 0.4 },
  'player.step.wood': { p: "A single footstep of a leather boot on old wooden planks, a hollow knock, close-miked, short", d: 0.5, t: 3, i: 0.65, max: 0.35 },
  'player.step.metal': { p: "A single footstep of a boot on an iron grate walkway, a metallic clank with a short ring, close-miked", d: 0.5, t: 3, i: 0.65, max: 0.45 },
  'player.gear': { p: "Small glass phials clinking softly together in a leather satchel with a light cloak rustle, one step, short", d: 0.6, t: 3, i: 0.6, max: 0.45 },
  'player.wade': { p: "Wading one step through waist-deep water, a sloshing swirl, close-miked, short", d: 0.8, t: 3, i: 0.6 },
  'player.crawl': { p: "Cloth and leather shuffling across gritty stone as someone crawls, a soft scrape, short", d: 0.6, t: 3, i: 0.6, max: 0.45 },
  'player.jump': { p: "A short cloak whoosh with a light boot scuff as someone jumps, quick, close-miked, dry", d: 0.5, t: 3, i: 0.6, max: 0.35 },
  'player.land.soft': { p: "A light landing on stone: a soft boot thump with a little grit, short, close-miked", d: 0.5, t: 3, i: 0.6, max: 0.35 },
  'player.land.hard': { p: "A heavy landing from a high fall onto stone: a deep boot thud, knees absorbing, grit and dust, short", d: 0.8, t: 2, i: 0.6 },
  'player.skid': { p: "Leather boots skidding briefly on gritty stone, a short scrape, close-miked", d: 0.5, t: 2, i: 0.6 },
  'player.grab': { p: "Gloved hands slapping onto a rough rock wall and gripping, a leather scrape, short, close-miked", d: 0.5, t: 2, i: 0.6 },
  'player.pullup': { p: "Someone hauling himself up over a stone ledge: cloth rustle and a scrape of boots on rock, short", d: 0.6, t: 2, i: 0.6 },
  'player.cramped': { p: "A felt hat brim bumping a low stone ceiling, a soft muffled thud with a trickle of grit, short", d: 0.5, t: 2, i: 0.6 },
  'player.kick': { p: "A forceful kick: a sharp gust of air and a low thump of force, short, punchy", d: 0.6, t: 2, i: 0.55 },
  'player.dive': { p: "A body dropping fast: a quick rising air whoosh with a cloak flapping, short", d: 0.6, t: 2, i: 0.55 },
  'player.slam': { p: "A heavy ground pound: a body slamming into stone from above, a deep booming thud with cracking rock and debris", d: 1, t: 2, i: 0.55 },
  'player.stomp': { p: "A boot stomping down onto a soft creature, a wet crunch and squish, short, punchy", d: 0.6, t: 2, i: 0.55 },
  'player.hurt': { p: "A man's short pained grunt, surprised, wordless, close-miked, dry", d: 0.6, t: 3, i: 0.5 },
  'player.death': { p: "A man's final strangled gasp as he collapses onto a stone floor with a body thud, wordless", d: 1.5, t: 2, i: 0.5 },
  'player.corpse.wand': { p: "A wooden staff clattering onto a stone floor with a couple of hollow bounces, short", d: 0.8, t: 2, i: 0.6 },
  'player.corpse.knell': { p: "A single low distant funeral bell toll echoing in a stone cavern, soft, long decay", d: 2.5, t: 1, i: 0.6 },
  'player.heartbeat': { p: "Two deep heavy heartbeat thumps, lub-dub, muffled, close, low frequency", d: 0.8, t: 2, i: 0.65 },
  'player.sputter': { p: "A small magical jet coughing and sputtering, put-put gasps of air like a failing engine, short", d: 0.6, t: 2, i: 0.55 },
  'player.levitate.loop': { p: "Steady soft magical levitation hum with an airy hiss of rushing air beneath, gentle and continuous", d: 3, t: 1, i: 0.5 },
  'player.vine': { p: "Hands grabbing a thick hanging vine: a leafy rustle and a creaking fibrous stretch, short", d: 0.5, t: 2, i: 0.6 },
  'player.teleport': { p: "A magical teleport: a sharp rising shimmering whoosh ending in a soft pop, short", d: 1, t: 2, i: 0.55 },
  'player.heal': { p: "A soft warm magical sparkle absorbed, a gentle rising glimmer, very short", d: 0.5, t: 2, i: 0.6 },
  'player.drink': { p: "A single gulp of liquid swallowed from a glass flask, close-miked, short", d: 0.5, t: 3, i: 0.65 },
  'player.recharge': { p: "A soft single warm magical chime pulse, gentle and quiet, short", d: 0.5, t: 1, i: 0.65 },
  'player.recharge.done': { p: "A warm rose-gold magical bloom: a soft chime swell with a shimmering airy halo, gentle, short", d: 1.4, t: 1, i: 0.55 },
  'player.staff': { p: "A hard wooden staff striking rock, a sharp crack with chips of stone skittering, short, close-miked", d: 0.5, t: 3, i: 0.6 },
  'player.glowseed': { p: "A small seed pod tossed with a soft whoosh and a faint magical twinkle, short", d: 0.5, t: 2, i: 0.6 },
  'player.club.swing': { p: "A long bony insect leg swung like a club, a heavy whooshing swipe through the air, short", d: 0.5, t: 2, i: 0.55 },
  'player.club.hit': { p: "A hard chitinous club smashing into a body, a crunchy thwack with a crack, short, punchy", d: 0.5, t: 2, i: 0.55 },
  'player.club.throw': { p: "A long object hurled end over end, a whirring spinning whoosh, short", d: 0.6, t: 1, i: 0.55 },
  'flask.siphon.loop': { p: "Continuous suction slurp of liquid drawn up through a narrow glass tube into a flask, bubbling gurgle", d: 3, t: 1, i: 0.5 },
  'flask.pour.loop': { p: "Continuous stream of liquid pouring out of a glass flask onto stone, glugging and splattering", d: 3, t: 1, i: 0.5 },
  'flask.throw': { p: "A glass bottle thrown, a short whoosh with liquid sloshing inside", d: 0.5, t: 2, i: 0.6 },
  'flask.shatter': { p: "A glass flask smashing on stone: bright shattering glass and a liquid splash, short", d: 0.8, t: 3, i: 0.6 },
  'flask.dry': { p: "A hollow tap on an empty glass bottle, a dull clink, short, dry", d: 0.5, t: 2, i: 0.7 },
  'wand.swap': { p: "A wooden wand drawn quickly from a leather holster, a short whick and a soft click, dry", d: 0.5, t: 2, i: 0.65 },
  'wand.dry': { p: "A wand fizzling out with no power: a hollow click and a tiny sad spark fizzle, short", d: 0.5, t: 2, i: 0.6 },
  'pickup.gold': { p: "Scooping up a small pile of gold nuggets, bright chunky clinks, short, close-miked", d: 0.6, t: 3, i: 0.6 },
  'pickup.coin': { p: "A single small gold coin landing and ringing with a bright clear ching, short", d: 0.5, t: 3, i: 0.65 },
  'pickup.generic': { p: "Picking up a small object: a soft grab with a bright little shimmer, short", d: 0.5, t: 2, i: 0.6 },
  'pickup.leg': { p: "Grabbing a long severed insect leg, a dry chitin rattle and a hollow knock, short", d: 0.6, t: 1, i: 0.6 },
  'pickup.heart': { p: "A crystal heart vessel absorbed: a deep warm pulse with a soft magical chime bloom", d: 1, t: 2, i: 0.55 },
  'pickup.chest': { p: "An old wooden treasure chest creaking open with a brass latch, and gold coins spilling out, short", d: 1.5, t: 2, i: 0.55 },
  'pickup.potion': { p: "Drinking a potion in three quick gulps, then a small satisfied glassy fizz, short", d: 1, t: 2, i: 0.55 },
  'pickup.key': { p: "A heavy golden key picked up, a bright metallic jingle with a sparkle, short", d: 0.8, t: 2, i: 0.6 },
  'pickup.bell': { p: "A small brass hand bell lifted, a clear bright ring with a gentle wobble, short", d: 1, t: 1, i: 0.6 },

  // -------------------------------------------------------------- spells
  'spell.spark.cast': { p: "A small crackling electric spark bolt fired from a wand: a sharp snap and a fast zipping buzz, short, punchy", d: 0.5, t: 3, i: 0.6 },
  'spell.spark.impact': { p: "A tiny electric bolt hitting a stone surface: a crisp crackling snap with a brief fizz, short", d: 0.5, t: 3, i: 0.6 },
  'spell.bomb.cast': { p: "A small iron bomb tossed from a hand, a short whoosh with a fizzing fuse", d: 0.5, t: 2, i: 0.55 },
  'spell.bomb.fuse.loop': { p: "Continuous short fizzing sputter of a lit bomb fuse, crackling sparks", d: 3, t: 1, i: 0.5 },
  'spell.lightning': { p: "A close lightning bolt strike: a sharp deafening crack with a sizzling electric tail and a quick rumble", d: 1.5, t: 3, i: 0.55 },
  'spell.flame.ignite': { p: "A gas burner igniting with a whoomp and a flare of fire, short", d: 0.6, t: 2, i: 0.6 },
  'spell.flame.loop': { p: "Continuous roaring flamethrower stream, steady whooshing fire with crackle", d: 3, t: 1, i: 0.5 },
  'spell.dig.loop': { p: "Continuous high-pitched magical grinding drill beam boring into rock, a gritty whine", d: 3, t: 1, i: 0.5 },
  'spell.warp.cast': { p: "A warping magical projectile launched: a phasing shimmer whoosh with a watery wobble, short", d: 0.7, t: 2, i: 0.55 },
  'spell.blackhole.loop': { p: "Continuous deep ominous gravitational vortex hum, swirling rushing air, a low drone", d: 3, t: 1, i: 0.5 },
  'spell.blackhole.implode': { p: "A vortex collapsing: air violently sucked inward in a rising reverse whoosh, then a deep sharp snap", d: 1.5, t: 2, i: 0.55, soft: true },
  'spell.vitriol.loop': { p: "Continuous hissing spray of acid from a nozzle, sizzling and fizzing as it spatters", d: 3, t: 1, i: 0.5 },
  'spell.cryojet.loop': { p: "Continuous freezing liquid nitrogen jet: a cold high-pressure hiss with crackling frost forming", d: 3, t: 1, i: 0.5 },
  'spell.aquajet.loop': { p: "Continuous water hose stream spraying hard and splattering on stone", d: 3, t: 1, i: 0.5 },
  'spell.frostshard.cast': { p: "A sharp ice shard launched, a crystalline whistle and a quick zip, short", d: 0.5, t: 3, i: 0.6 },
  'spell.icelance.cast': { p: "A heavy ice lance hurled, a glassy ringing whoosh with frosty crackle, short", d: 0.7, t: 2, i: 0.55 },
  'spell.ice.impact': { p: "An ice shard shattering on impact, a crystalline crunch and tinkling fragments, short", d: 0.6, t: 3, i: 0.6 },
  'spell.freeze': { p: "Water crackling and freezing solid into ice, crisp crystalline creaks and snaps, short", d: 1, t: 2, i: 0.55 },
  'spell.wisp.cast': { p: "An ethereal wisp spirit released, an airy whistling glide with a soft glassy chime", d: 0.7, t: 2, i: 0.55 },
  'spell.wisp.loop': { p: "Continuous soft ethereal whispering hum, a gentle airy magic shimmer", d: 3, t: 1, i: 0.5 },
  'spell.meteor.cast': { p: "A heavy molten rock launched, a low fiery whoomph with crackling embers", d: 0.8, t: 2, i: 0.55 },
  'spell.meteor.loop': { p: "Continuous roar of a burning rock flying through the air, a fiery rushing rumble", d: 3, t: 1, i: 0.5 },
  'spell.conjure': { p: "A stone slab grinding rapidly up out of the ground, a rocky crunch and a settling thud, short", d: 0.8, t: 2, i: 0.55 },
  'spell.vitrify': { p: "Liquid instantly hardening into glass: a bright crystalline crackle and a ringing glassy tone", d: 1, t: 2, i: 0.55 },
  'spell.emberstorm': { p: "A fountain of glowing embers bursting upward, crackling sparks and a fiery whoosh", d: 1.2, t: 2, i: 0.55 },
  'spell.crit.wet': { p: "A heavy wet splat with a bright splash ping, short, punchy", d: 0.5, t: 2, i: 0.6 },
  'spell.crit.shatter': { p: "A frozen target shattering: a loud crisp ice crack and a bright crystalline burst, short", d: 0.6, t: 2, i: 0.6 },
  'spell.crit.pyre': { p: "A burst of flame erupting: a fiery whump with crackle, short, punchy", d: 0.6, t: 2, i: 0.6 },
  'spell.charge.electric': { p: "A quick electric static zap and crackle, short", d: 0.5, t: 2, i: 0.65 },
  'spell.charge.frost': { p: "A quick frosty chill: a crisp icy tinkle and a soft crackle, short", d: 0.5, t: 2, i: 0.65 },
  'trick.whip': { p: "A rising whip-like whoosh building tension, an airy swoosh accelerating upward, short", d: 1, t: 1, i: 0.55, soft: true },
  'trick.shellcrack': { p: "A hard insect shell cracking loudly, a dry brittle crunch with a hollow pop, short", d: 0.8, t: 2, i: 0.6 },

  // --------------------------------------------------------------- world
  'boom.small': { p: "A small explosion in a stone cave: a sharp bang with a short burst of debris patter, short tail", d: 1.2, t: 3, i: 0.55 },
  'boom.medium': { p: "A gunpowder explosion in a stone cavern: a punchy boom with rock debris raining down, medium tail", d: 2, t: 3, i: 0.55 },
  'boom.large': { p: "A huge explosion in a vast underground cavern: a deep concussive boom, a long rumbling tail and falling rubble", d: 3.5, t: 2, i: 0.55 },
  'mat.zap': { p: "An electric arc zap: a sharp crackling buzz, short", d: 0.5, t: 3, i: 0.65 },
  'mat.shatter': { p: "Glass and ice breaking: a bright crack and a cascade of tinkling shards, short", d: 0.8, t: 3, i: 0.6 },
  'mat.steam': { p: "Water flashing to steam on hot lava: an airy sharp hiss, short", d: 0.8, t: 3, i: 0.6 },
  'mat.sizzle': { p: "A small fire crackling and sizzling, short", d: 0.6, t: 2, i: 0.6 },
  'mat.ignite': { p: "Fire catching with a whoosh, a brazier bursting into flame, short", d: 1, t: 2, i: 0.55 },
  'mat.squelch': { p: "A wet slimy squelch, gooey and organic, short", d: 0.6, t: 3, i: 0.6 },
  'mat.bubble': { p: "A single thick bubble bursting in a bubbling cauldron, blub, short", d: 0.5, t: 3, i: 0.65 },
  'mat.splash.small': { p: "A small object splashing into water, a short splash", d: 0.6, t: 3, i: 0.6 },
  'mat.splash.big': { p: "A heavy body plunging into a deep pool, a big splash and slosh, short", d: 1, t: 2, i: 0.55 },
  'mat.drip': { p: "A single water drop falling into a still underground pool, a clear plink with a cave echo", d: 0.8, t: 4, i: 0.65 },
  'mat.hollow': { p: "A hollow knock on a thin stone wall with an empty cavity behind it, resonant, short", d: 0.6, t: 2, i: 0.6 },
  'mat.fire.loop': { p: "Continuous crackling bonfire, roaring flames and popping wood", d: 3, t: 1, i: 0.5 },
  'mat.lava.loop': { p: "Continuous thick bubbling molten lava, slow heavy gloops and a low hot rumble", d: 3, t: 1, i: 0.5 },
  'mat.water.loop': { p: "Continuous water flowing and trickling over stones in a cave", d: 3, t: 1, i: 0.5 },
  'mat.acid.loop': { p: "Continuous acid fizzing and dissolving, a bubbling sizzle", d: 3, t: 1, i: 0.5 },
  'mat.steam.loop': { p: "Continuous steam hissing from vents, a soft airy roar", d: 3, t: 1, i: 0.5 },
  'mat.electric.loop': { p: "Continuous electric crackling, arcing static buzz on metal", d: 3, t: 1, i: 0.5 },
  'mat.fuse.loop': { p: "Continuous black powder fuse burning, fizzing and sputtering sparks", d: 3, t: 1, i: 0.5 },
  'body.impact.wood': { p: "A wooden crate thudding against stone, a hollow knock, short", d: 0.5, t: 3, i: 0.6 },
  'body.impact.stone': { p: "A heavy stone block knocking against rock, a dull thud with grit, short", d: 0.5, t: 3, i: 0.6 },
  'body.impact.metal': { p: "An iron weight clanging against stone, a metallic clank, short", d: 0.5, t: 3, i: 0.6 },
  'body.smash.wood': { p: "A wooden crate smashed apart, splintering planks and scattering debris, short", d: 1, t: 2, i: 0.55 },
  'body.smash.stone': { p: "A stone block cracking apart into rubble, a crunchy rock break and debris, short", d: 1, t: 2, i: 0.55 },
  'body.smash.metal': { p: "An iron box crushed and burst open, a metal crunch and clattering pieces, short", d: 1, t: 1, i: 0.55 },
  'body.bash': { p: "A heavy crate slamming into a creature, a blunt thump of impact, short", d: 0.5, t: 2, i: 0.6 },
  'body.grab': { p: "A quick magical grab: a soft snap of force, short", d: 0.5, t: 2, i: 0.6 },
  'body.lift': { p: "A telekinetic lift: a soft rising magical hum swell, short", d: 0.6, t: 2, i: 0.6 },
  'body.throw': { p: "A heavy object flung with a strong whoosh, short", d: 0.5, t: 2, i: 0.6 },
  'body.drop': { p: "An object gently released and dropped with a soft thump, short", d: 0.5, t: 1, i: 0.6 },
  'body.rip': { p: "Old wood cracking under strain, a single creak and a small splinter crack, short", d: 0.5, t: 3, i: 0.6 },
  'body.tear': { p: "A wooden plank torn free from a wall with a loud splintering rip, short", d: 0.8, t: 2, i: 0.55 },
  'body.burnout': { p: "Burnt wood collapsing into embers and ash, a soft crumble with a hiss", d: 1, t: 1, i: 0.55 },
  'world.portal': { p: "A great stone gate unlocking: a deep resonant bell ringing in a lock, then heavy stone grinding open under a rising magical whoosh", d: 2.5, t: 1, i: 0.5 },
  'world.gong': { p: "A deep bronze gong struck once, rich overtones, a long rolling decay through caves", d: 3, t: 2, i: 0.6 },
  'world.waystone': { p: "Two bright clear chime tones rising, a small magical confirmation, short", d: 1, t: 1, i: 0.6 },
  'mech.lever': { p: "A heavy iron lever thrown with a ratcheting clunk, mechanical, short", d: 0.6, t: 2, i: 0.6 },
  'mech.grip': { p: "A gloved hand gripping a cold iron handle, a leather squeak and a metal tap, short", d: 0.5, t: 1, i: 0.6 },
  'mech.door': { p: "A heavy iron door grinding along stone rails, a rumbling scrape ending in a clank", d: 1.5, t: 2, i: 0.55 },
  'mech.groan': { p: "A large broken machine groaning: a deep metal creak and strained grinding, ominous", d: 1.5, t: 2, i: 0.55 },
  'mech.plate': { p: "A stone pressure plate pressed down with a deep click and a mechanical thunk, short", d: 0.6, t: 2, i: 0.6 },
  'mech.scale': { p: "A heavy brass weighing scale tipping with a clank and a chain rattle, short", d: 0.8, t: 1, i: 0.6 },
  'mech.buoy': { p: "A float rising in water with a glug and a brass lever clank, short", d: 0.8, t: 1, i: 0.6 },
  'mech.latch': { p: "An electrical relay snapping shut: a metallic clack with a sharp electric zap, short", d: 0.6, t: 1, i: 0.6 },
  'mech.sensor': { p: "A soft brass mechanism tick engaging, short, quiet", d: 0.5, t: 1, i: 0.65 },
  'mech.counterweight': { p: "A heavy iron counterweight dropping with a rattling chain and a deep clunk", d: 1, t: 1, i: 0.55 },
  'mech.vault': { p: "A heavy vault door unsealing: a hiss of air, bolts retracting and a deep stone rumble", d: 1.5, t: 1, i: 0.55 },
  'mech.sequence.step': { p: "A single clear brass chime tone, bright and short", d: 0.6, t: 1, i: 0.65 },
  'mech.sequence.fail': { p: "A sour mechanical buzz and a clunk of gears resetting, short", d: 0.6, t: 1, i: 0.6 },
  'mech.relay.arm': { p: "A clockwork mechanism winding and ticking, short", d: 0.6, t: 1, i: 0.6 },
  'mech.relay.fire': { p: "A spring-loaded mechanism releasing with a sharp clack and a whirr, short", d: 0.6, t: 1, i: 0.6 },
  'mech.dispenser': { p: "A hatch dropping open and a crate tumbling out with a thud, short", d: 0.8, t: 1, i: 0.6 },
  'mech.plug': { p: "A stone plug cracking and crumbling apart, rock debris falling, short", d: 1, t: 1, i: 0.55 },
  'mech.rune': { p: "A magic rune struck: a resonant shimmering chime rising, with a distant deep stone rumble", d: 1.5, t: 1, i: 0.55 },
  'mech.shrine': { p: "A soft warm humming chime of a small shrine, gentle and quiet, short", d: 1, t: 1, i: 0.6 },
  'mech.cauldron': { p: "A cauldron brew completing: a rich bubbling surge and a bright magical chime pop", d: 1.2, t: 1, i: 0.55 },
  'critter.chirp': { p: "A single cave cricket chirp, tiny and quiet, short", d: 0.5, t: 3, i: 0.65 },
  'critter.skitter': { p: "A small beetle skittering quickly across stone, tiny dry clicks, short", d: 0.5, t: 3, i: 0.65 },
  'creature.hit': { p: "A punchy hit on a creature: a short fleshy thwack, close-miked", d: 0.5, t: 3, i: 0.6 },
  'creature.gib': { p: "A creature smashed against a wall: a wet meaty crunch and splatter, short", d: 0.8, t: 2, i: 0.55 },
  'creature.dodge': { p: "A quick airy whiff of a creature leaping aside, short", d: 0.5, t: 2, i: 0.6 },
  'creature.hop': { p: "A small soft body landing and launching: a soft pat, short", d: 0.5, t: 2, i: 0.6 },
  'creature.generic.alert': { p: "A small cave creature's sharp alarmed chirp, short", d: 0.5, t: 2, i: 0.6 },
  'creature.generic.hurt': { p: "A small cave creature's pained squeal, short", d: 0.5, t: 2, i: 0.6 },
  'creature.generic.death': { p: "A small cave creature's dying screech fading away, short", d: 0.8, t: 2, i: 0.55 },
  'proj.fireball.loop': { p: "Continuous whooshing roar of a small fireball flying through the air", d: 3, t: 1, i: 0.5 },

  // ------------------------------------------------ Bell & Tea Engine (D1)
  'tea.striker': { p: "A flint striker scraping and sparking, then a black powder fuse catching with a fizzing hiss", d: 1.2, t: 1, i: 0.55 },
  'tea.cap': { p: "A percussion cap firing: a sharp small pop and a crackle of sparks", d: 0.6, t: 1, i: 0.6 },
  'tea.fault': { p: "A comedic machine failure: a dull hollow clonk and a gear winding down with a sad creak", d: 1.2, t: 1, i: 0.55 },
  'tea.knocker': { p: "A clockwork knocker winding up with ticks, then whacking a hanging iron weight with a solid thunk", d: 1.2, t: 1, i: 0.55 },
  'tea.advance': { p: "A small brass ratchet click as a mechanism advances one notch, short", d: 0.5, t: 2, i: 0.65 },
  'tea.pendulum': { p: "A heavy iron pendulum released: a creaking rope, a great whoosh, then a stone boulder struck with a heavy knock", d: 2, t: 1, i: 0.5 },
  'tea.boulder': { p: "A heavy stone boulder rolling down a wooden ramp, a rumbling roll over creaking planks", d: 2.5, t: 1, i: 0.55 },
  'tea.dominoes': { p: "Six large wooden dominoes toppling one after another in a clattering chain, then a latch clicks", d: 2, t: 1, i: 0.55 },
  'tea.spring': { p: "A wound clockwork spring releasing: a fast whirring crank spin and a whipping cable snap", d: 1.5, t: 1, i: 0.55 },
  'tea.duck': { p: "A rubber duck squeak followed by a gentle water drip into a basin", d: 1, t: 1, i: 0.6 },
  'tea.marble': { p: "A steel marble rolling fast along a long brass rail, a rumbling roll ending in a sharp flint strike", d: 2.5, t: 1, i: 0.55 },
  'tea.generator': { p: "A copper coil generator surging to life: a rising electric hum and crackling current", d: 1.8, t: 1, i: 0.55, soft: true },
  'tea.magnet': { p: "An electromagnet energizing with a rising hum, then an iron latch yanked free with a loud clank", d: 1.5, t: 1, i: 0.55, soft: true },
  'tea.counterweight': { p: "A heavy counterweight descending on squeaking pulleys and rattling chains, ending in a clunk", d: 2.5, t: 1, i: 0.55 },
  'tea.served': { p: "A copper kettle whistle rising to a shrill peak, then a small brass bell rung twice, cheerful", d: 3, t: 1, i: 0.55, soft: true },

  // ------------------------------------------------------------- ambience
  'amb.bellows': { p: 'Ambience of a vast Victorian underground waterworks: slow rhythmic mechanical bellows breathing, distant steam pipes hissing, occasional metal creaks, water drips echoing in brick cisterns, a low machinery hum', d: 28, t: 1, i: 0.45, stereo: true },
  'amb.rot': { p: 'Ambience of a damp underground fungal garden: dense quiet insect chirrs and clicks, soft spore puffs, wet roots creaking, slow drips, a faint bubbling marsh', d: 28, t: 1, i: 0.45, stereo: true },
  'amb.cisterns': { p: 'Ambience of a flooded Victorian stone cistern: gentle water lapping against stone, echoing drips in a huge vaulted chamber, a deep low rumble, distant trickles', d: 28, t: 1, i: 0.45, stereo: true },
  'amb.kiln': { p: 'Ambience inside a volcanic furnace: roaring heat, slowly bubbling lava, deep rumbling, distant rhythmic anvil strikes echoing, crackling embers', d: 28, t: 1, i: 0.45, stereo: true },
  'amb.breath.inhale': { p: "An enormous mechanical bellows slowly drawing in air through iron pipes: a long rising whoosh with groaning leather and creaking metal", d: 8, t: 1, i: 0.5, soft: true },
  'amb.breath.exhale': { p: "A massive bellows exhaling: pressurized steam blasting through iron pipes with a roaring hiss, then slowly easing off", d: 10, t: 1, i: 0.5, soft: true },
  'amb.breath.jet': { p: "Continuous high-pressure steam jet blasting from a brass nozzle, a loud roaring hiss", d: 3, t: 1, i: 0.5 },

  // ------------------------------------------------------------ creatures
  // Weaver: an eight-legged lair guardian of ivory chitin.
  'creature.weaver.step': { p: "Dry chitinous spider legs tapping quickly on stone, two or three light clicks, short", d: 0.5, t: 4, i: 0.6, max: 0.3 },
  'creature.weaver.idle': { p: "A large insect's dry clicking stridulation chirr, quiet and curious, short", d: 1, t: 2, i: 0.55 },
  'creature.weaver.alert': { p: "A giant spider-like creature's sharp rising chittering hiss of alarm, dry and clicky, short", d: 0.8, t: 2, i: 0.55 },
  'creature.weaver.chirr': { p: "A giant insect's rapid buzzing chirr, a dry stridulation, short", d: 0.8, t: 3, i: 0.55 },
  'creature.weaver.pounce': { p: "A giant spider leaping: a sharp chittering screech with a scrabble of legs, short", d: 0.6, t: 2, i: 0.55 },
  'creature.weaver.windup': { p: "A spider-like creature rearing up: a rapid dry clicking rattle building, short", d: 0.6, t: 2, i: 0.55 },
  'creature.weaver.strike': { p: "A sharp chitin needle stabbing into stone, a hard crack and a gritty knock, short", d: 0.6, t: 2, i: 0.6 },
  'creature.weaver.spit': { p: "A creature spitting a sticky silk thread, a wet-dry hiss and flick, short", d: 0.6, t: 2, i: 0.55 },
  'creature.weaver.silk': { p: "Silk thread spun fast from a spinneret, a dry fibrous hiss, short", d: 0.8, t: 2, i: 0.55 },
  'creature.weaver.feed': { p: "A giant insect crunching and chewing on a small bug, dry mandible clicks and crunches, short", d: 0.8, t: 2, i: 0.55 },
  'creature.weaver.hurt': { p: "A giant spider-like creature's pained screeching chitter, short", d: 0.5, t: 2, i: 0.55 },
  'creature.weaver.death': { p: "A giant spider dying: cracking chitin, a shrill fading chittering screech and legs clattering down", d: 1.4, t: 2, i: 0.5 },
  'creature.weaver.sever': { p: "An insect leg snapping off: a brittle chitin crack and a wet pop, short", d: 0.6, t: 2, i: 0.6 },
  'creature.weaver.limbhit': { p: "A thin chitinous leg struck: a dry tap and a small crack, short", d: 0.5, t: 2, i: 0.6 },
  // Rillback: a silt eel whose spine comes alive in liquid.
  'creature.rillback.move': { p: "A slippery eel wriggling through wet silt, a slithering squish, short", d: 0.8, t: 3, i: 0.55 },
  'creature.rillback.idle': { p: "A small eel-like creature gurgling softly underwater, a bubbly chirp, short", d: 1, t: 2, i: 0.55 },
  'creature.rillback.alert': { p: "An eel-like creature's wet hissing gurgle of alarm, short", d: 0.8, t: 2, i: 0.55 },
  'creature.rillback.windup': { p: "An eel coiling tight in water, a wet tensing slither and a low hiss, short", d: 0.6, t: 2, i: 0.55 },
  'creature.rillback.lunge': { p: "A fast eel lunge through water, a sharp wet whoosh and snap, short", d: 0.5, t: 2, i: 0.55 },
  'creature.rillback.charge': { p: "An electric eel charging up: a rising humming electric buzz underwater, short", d: 1, t: 2, i: 0.55, soft: true },
  'creature.rillback.discharge': { p: "An electric eel discharging into water: a crackling zap and fizzing bubbles, short", d: 0.8, t: 2, i: 0.55 },
  'creature.rillback.flop': { p: "A beached eel flopping on wet stone, a wet slap, short", d: 0.5, t: 2, i: 0.6 },
  'creature.rillback.hurt': { p: "An eel-like creature's pained wet squeal, short", d: 0.5, t: 2, i: 0.55 },
  'creature.rillback.death': { p: "An eel creature dying: a gurgling wet shriek fading into bubbles, short", d: 1.2, t: 2, i: 0.5 },
  // Root Loper: a Tanglewrist predator of living wood.
  'creature.rootloper.step': { p: "A creature of living roots stepping: creaking wood and rustling fibres, short", d: 0.6, t: 3, i: 0.55, max: 0.45 },
  'creature.rootloper.idle': { p: "A living root creature creaking softly like an old tree in the wind, short", d: 1.2, t: 2, i: 0.55 },
  'creature.rootloper.alert': { p: "A wooden root creature's low groaning creak rising to a rasping hiss, short", d: 1, t: 2, i: 0.55 },
  'creature.rootloper.windup': { p: "Wooden roots tensing and creaking under strain like a drawn bow, short", d: 0.6, t: 2, i: 0.55 },
  'creature.rootloper.attack': { p: "A whip of wooden roots lashing out: a whooshing swipe and a fibrous crack, short", d: 0.6, t: 2, i: 0.55 },
  'creature.rootloper.hurt': { p: "Wood cracking under a blow with a pained creature groan, short", d: 0.6, t: 2, i: 0.55 },
  'creature.rootloper.death': { p: "A root creature dying: splintering wood, a long collapsing creak and falling twigs", d: 1.4, t: 2, i: 0.5 },
  // Stone Maw: a blind burrower that listens through rock.
  'creature.stonemaw.idle': { p: "A stone creature grinding its jaws slowly, a low gravelly rumble, short", d: 1.2, t: 2, i: 0.55 },
  'creature.stonemaw.alert': { p: "A stone beast's deep grinding roar with rattling gravel, short", d: 1, t: 2, i: 0.55 },
  'creature.stonemaw.windup': { p: "Stone jaws grinding open with gravel falling, short", d: 0.6, t: 2, i: 0.55 },
  'creature.stonemaw.bite': { p: "Huge stone jaws snapping shut, a crunching rock impact, short, punchy", d: 0.6, t: 2, i: 0.6 },
  'creature.stonemaw.chew': { p: "Stone jaws chewing through rock, a crunching gravel grind, short", d: 0.8, t: 2, i: 0.55 },
  'creature.stonemaw.hurt': { p: "A stone creature cracking with a pained grinding groan, short", d: 0.6, t: 2, i: 0.55 },
  'creature.stonemaw.death': { p: "A stone beast crumbling apart: cracking rock, a dying low rumble and rubble falling", d: 1.5, t: 2, i: 0.5 },
  // Bat: sleeps on ceilings, wakes as a flutter of leather.
  'creature.bat.idle': { p: "A cave bat's leathery wings fluttering with faint high squeaks, short", d: 1, t: 2, i: 0.55 },
  'creature.bat.wake': { p: "A bat waking and dropping from a ceiling: a sudden wing flap and a squeak, short", d: 0.6, t: 2, i: 0.55 },
  'creature.bat.swoop': { p: "A bat swooping fast: a leathery wing whoosh and a sharp squeak, short", d: 0.6, t: 2, i: 0.55 },
  'creature.bat.alert': { p: "A cave bat's sharp high-pitched squeak, short", d: 0.5, t: 2, i: 0.6 },
  'creature.bat.slimed': { p: "A bat's wings gummed with slime: sticky wet flapping and a distressed squeak, short", d: 0.6, t: 1, i: 0.55 },
  'creature.bat.hurt': { p: "A bat's pained shriek, short", d: 0.5, t: 2, i: 0.6 },
  'creature.bat.death': { p: "A bat's dying squeal and a soft thump as it falls, short", d: 0.8, t: 2, i: 0.55 },
  // Slime: squash-and-stretch hopper.
  'creature.slime.idle': { p: "A slime creature wobbling, a soft gloopy jiggle, short", d: 0.8, t: 2, i: 0.55 },
  'creature.slime.hop': { p: "A slime blob hopping: a squishy boing and a wet slap landing, short", d: 0.5, t: 3, i: 0.6 },
  'creature.slime.alert': { p: "A slime creature's gurgling blorp of alarm, short", d: 0.6, t: 2, i: 0.55 },
  'creature.slime.attack': { p: "A slime blob lunging and biting: a wet squelchy chomp, short", d: 0.5, t: 2, i: 0.6 },
  'creature.slime.hurt': { p: "A slime creature hit: a wet splat and a gloopy squeal, short", d: 0.5, t: 2, i: 0.6 },
  'creature.slime.death': { p: "A slime creature bursting: a big wet splatter pop, short", d: 0.8, t: 2, i: 0.55 },
  // Acid slime: its blood eats the floor.
  'creature.acidslime.idle': { p: "An acidic slime blob wobbling with a soft fizzing sizzle, short", d: 0.8, t: 2, i: 0.55 },
  'creature.acidslime.hop': { p: "An acid slime hopping: a squishy boing with a fizzing hiss, short", d: 0.5, t: 2, i: 0.6 },
  'creature.acidslime.alert': { p: "An acid slime's bubbling hiss of alarm, short", d: 0.6, t: 2, i: 0.55 },
  'creature.acidslime.attack': { p: "An acid slime biting: a wet squelch and a sharp acidic sizzle, short", d: 0.5, t: 2, i: 0.6 },
  'creature.acidslime.hurt': { p: "An acid slime hit: a wet splat with fizzing, short", d: 0.5, t: 2, i: 0.6 },
  'creature.acidslime.death': { p: "An acid slime bursting: a wet pop and a hissing acid sizzle, short", d: 0.8, t: 2, i: 0.55 },
  // Eggs: a clutch. It is not dormant.
  'creature.eggs.idle': { p: "A cluster of wet eggs pulsing, a soft slimy throbbing squelch, quiet, short", d: 1, t: 1, i: 0.55 },
  'creature.eggs.hatch': { p: "Slimy eggs hatching: wet cracking shells and squishy slurps as little things wriggle out", d: 1.2, t: 2, i: 0.55 },
  'creature.eggs.hurt': { p: "A wet egg sac punctured, a squishy pop, short", d: 0.5, t: 1, i: 0.6 },
  'creature.eggs.death': { p: "A clutch of eggs bursting apart, wet splattering pops, short", d: 0.8, t: 1, i: 0.55 },
  // Spitter: lobs corrosive gobs from range.
  'creature.spitter.step': { p: "A small lizard creature's claws skittering on stone, short", d: 0.5, t: 3, i: 0.6, max: 0.3 },
  'creature.spitter.idle': { p: "A small lizard creature clicking its throat, a quiet gurgle, short", d: 0.8, t: 2, i: 0.55 },
  'creature.spitter.alert': { p: "A lizard-like creature's hissing croak, short", d: 0.6, t: 2, i: 0.55 },
  'creature.spitter.spit': { p: "A creature hawking and spitting a gob of corrosive acid, a wet launch, short", d: 0.6, t: 2, i: 0.55 },
  'creature.spitter.hurt': { p: "A lizard creature's pained hissing squeak, short", d: 0.5, t: 2, i: 0.55 },
  'creature.spitter.death': { p: "A lizard creature's gurgling dying croak, short", d: 0.8, t: 2, i: 0.55 },
  // Bomber: walks its payload to you, fuse first.
  'creature.bomber.idle': { p: "A small goblin-like creature giggling nervously, wordless, short", d: 0.8, t: 2, i: 0.5 },
  'creature.bomber.alert': { p: "A small goblin creature's excited wordless cackle, short", d: 0.8, t: 2, i: 0.5 },
  'creature.bomber.fuse': { p: "A bomb fuse lit with a sharp fizz and sputtering sparks, over a small creature's gleeful wordless cackle", d: 1.2, t: 2, i: 0.5 },
  'creature.bomber.hurt': { p: "A small goblin creature's startled wordless yelp, short", d: 0.5, t: 2, i: 0.5 },
  'creature.bomber.death': { p: "A small goblin creature's wordless squawk cut short", d: 0.6, t: 2, i: 0.5 },
  // Imp: fire-born.
  'creature.imp.idle': { p: "A small fire imp's crackling wordless snicker, embers popping, short", d: 0.8, t: 2, i: 0.5 },
  'creature.imp.alert': { p: "A fire imp's shrill mischievous wordless cackle with a flare of flame, short", d: 0.8, t: 2, i: 0.5 },
  'creature.imp.cast': { p: "A fire imp hurling a fireball: a fiery whoosh and a crackling burst, short", d: 0.8, t: 2, i: 0.55 },
  'creature.imp.hurt': { p: "A fire imp's hissing screech like water on embers, short", d: 0.5, t: 2, i: 0.55 },
  'creature.imp.death': { p: "A fire imp snuffed out: a sizzling screech fading into a puff of steam, short", d: 1, t: 2, i: 0.5 },
  // Golem: a heavy strider with a pulsing core and steam thrusters.
  'creature.golem.step': { p: "A heavy stone golem footstep, a deep thud with a grinding stone creak, short", d: 0.6, t: 3, i: 0.55 },
  'creature.golem.alert': { p: "A stone golem's deep resonant mechanical rumble and a humming core, short", d: 1.2, t: 2, i: 0.55 },
  'creature.golem.jet': { p: "Steam thrusters igniting with a roaring hiss and a rumbling blast, short", d: 1.2, t: 2, i: 0.55 },
  'creature.golem.punch': { p: "A massive stone fist pounding a rock wall, a heavy crunching boom, short", d: 0.8, t: 2, i: 0.55 },
  'creature.golem.throw': { p: "A stone golem hurling a boulder: heavy grinding and a big whoosh, short", d: 0.8, t: 2, i: 0.55 },
  'creature.golem.hurt': { p: "A stone golem hit: cracking stone and a low mechanical groan, short", d: 0.6, t: 2, i: 0.55 },
  'creature.golem.death': { p: "A stone golem collapsing: cracking stone, a powering-down hum and a heavy crash of rubble", d: 1.8, t: 2, i: 0.5 },
  // Wisp: a guttering diamond of frost light.
  'creature.wisp.idle': { p: "A frost wisp humming: a soft icy crystalline shimmer, quiet, short", d: 1, t: 2, i: 0.55 },
  'creature.wisp.alert': { p: "A frost wisp flaring: a bright crystalline chime swell with a cold whoosh, short", d: 0.8, t: 2, i: 0.55 },
  'creature.wisp.cast': { p: "A frost wisp firing an ice bolt: a glassy chime and an icy zip, short", d: 0.6, t: 2, i: 0.55 },
  'creature.wisp.hurt': { p: "A frost wisp flickering: a crackling icy glitch and a thin glassy whine, short", d: 0.5, t: 2, i: 0.55 },
  'creature.wisp.death': { p: "A frost wisp shattering: bursting ice crystals and a fading glassy chime, short", d: 1, t: 2, i: 0.55 },
  // Mage: a hooded telekinetic.
  'creature.mage.alert': { p: "A hooded sorcerer's low menacing wordless hum and a crackle of magic, short", d: 0.8, t: 2, i: 0.5 },
  'creature.mage.cast': { p: "Telekinetic magic ripping stones loose: a low rumbling surge and a burst of flying debris, short", d: 1, t: 2, i: 0.55 },
  'creature.mage.shard': { p: "A sorcerer flinging stone shards: a sharp magical whoosh with rattling fragments, short", d: 0.8, t: 2, i: 0.55 },
  'creature.mage.blink': { p: "A sorcerer teleporting: a magical pop and a quick reverse whoosh, short", d: 0.6, t: 2, i: 0.55 },
  'creature.mage.hurt': { p: "A hooded sorcerer's pained wordless grunt with a magical crackle, short", d: 0.5, t: 2, i: 0.5 },
  'creature.mage.death': { p: "A sorcerer's magic unravelling: a fading distorted wail and a dissipating magical rush", d: 1.4, t: 2, i: 0.5 },
  // The Sunken Leviathan (floor 3 boss): water is its armour.
  'creature.leviathan.idle': { p: "A colossal underwater beast's deep slow breathing churn, huge bubbles rising, low and ominous", d: 3, t: 1, i: 0.5, soft: true },
  'creature.leviathan.alert': { p: "A colossal sea serpent's deep bellowing roar rising from underwater, churning water and huge bubbles", d: 3, t: 2, i: 0.5 },
  'creature.leviathan.glance': { p: "A blow glancing off a creature's wet armoured hide underwater: a dull plink and a muffled splash, short", d: 0.5, t: 2, i: 0.6 },
  'creature.leviathan.spit': { p: "A giant sea beast spewing a blast of water, a powerful gushing spray, short", d: 1.2, t: 2, i: 0.55 },
  'creature.leviathan.windup': { p: "A giant sea serpent inhaling and coiling, a rising deep growl and churning water, short", d: 1.2, t: 2, i: 0.55, soft: true },
  'creature.leviathan.lunge': { p: "A giant sea serpent lunging out of the water: a massive splash and a snapping roar, short", d: 1.2, t: 2, i: 0.55 },
  'creature.leviathan.flop': { p: "A giant beached sea creature heaving and flopping on stone, a heavy wet slam and a groan", d: 1.2, t: 2, i: 0.55 },
  'creature.leviathan.hurt': { p: "A giant sea serpent's pained bellow, wet and deep, short", d: 1, t: 2, i: 0.55 },
  'creature.leviathan.death': { p: "A colossal sea serpent dying: a long agonized deep roar sinking into gurgling water and a heavy final splash", d: 3.5, t: 1, i: 0.5 },
  // The Kiln Colossus (floor 4 boss): water is the strategy.
  'creature.colossus.idle': { p: "A giant of molten rock breathing: a deep slow rumble, crackling magma and hissing heat", d: 3, t: 1, i: 0.5, soft: true },
  'creature.colossus.alert': { p: "A colossal magma giant's thunderous deep roar with rumbling rock and a roar of fire", d: 3, t: 2, i: 0.5 },
  'creature.colossus.step': { p: "A colossal stone giant's footstep: a huge earth-shaking boom with cracking rock, short", d: 1, t: 3, i: 0.55 },
  'creature.colossus.volley': { p: "A magma giant hurling a volley of fireballs: a deep roaring whoosh and crackling flames", d: 1.5, t: 2, i: 0.55 },
  'creature.colossus.hurt': { p: "A magma giant hit: cracking stone and a deep angry growl with hissing lava, short", d: 1, t: 2, i: 0.55 },
  'creature.colossus.death': { p: "A colossal magma giant collapsing: a final deep dying roar and a huge rumbling crumble of rock and fire", d: 4, t: 1, i: 0.5 },
};
