// Generated by scripts/audio/gen-arena-music.mjs.
import type { ScoreTrack } from '@/content/audio/scoreTypes';
export const ARENA_SCORE_TRACKS: readonly ScoreTrack[] = [
  {
    "id": "arena-battle",
    "url": "audio/music/arena/arena-battle.mp3",
    "label": "Foundry clash",
    "group": "Score · Arena",
    "role": "arena",
    "floor": null,
    "loop": true,
    "gaplessLoop": true,
    "key": "D minor / F major",
    "bpm": 156,
    "seconds": 110.77000000000001,
    "headSec": 0,
    "tailSec": 0,
    "lufs": -15.9,
    "bytes": 2300743,
    "summary": "Original instrumental fantasy platform fighting game music. Live-sounding orchestra and tight rock rhythm section: soaring French horns and trumpets, racing spiccato strings, punchy acoustic drums, electric bass and crisp rhythm guitar. Brass melody is memorable and singable, with a clear original eight-bar motif. Confident, playful, heroic competition in a huge copper-and-stone alchemical foundry lit by molten gold and teal lamps. Clean modern game soundtrack mix, articulate transients, controlled bass, room for combat sound effects. No vocals, choir, speech, ambient drones, music box, horror, chiptune, trailer risers or imitation of an existing song. MAIN BATTLE THEME. 156 BPM, 4/4, D minor with bright F major lifts. Start immediately on a strong downbeat with full rhythmic drive, no slow introduction. First 30 seconds: brass states the bold motif over racing strings, syncopated guitar and snare backbeat. Next 30 seconds: adventurous answering melody in upper strings, brass punctuation and tom fills, keep the groove moving. Next 30 seconds: triumphant full-orchestra return, countermelody and cymbal accents. Final 30 seconds: exciting variation returning to the opening harmony and groove. Sustain energy until the very end, no ritardando, no long fade or final resolving chord. Written as a repeatable continuous battle loop. Competitive and joyful, never gloomy or exhausting."
  },
  {
    "id": "arena-lobby",
    "url": "audio/music/arena/arena-lobby.mp3",
    "label": "Challengers assemble",
    "group": "Score · Arena",
    "role": "arena",
    "floor": null,
    "loop": true,
    "gaplessLoop": true,
    "key": "F major",
    "bpm": 126,
    "seconds": 30.48,
    "headSec": 0,
    "tailSec": 0,
    "lufs": -16,
    "bytes": 634138,
    "summary": "Original instrumental fantasy platform fighting game music. Live-sounding orchestra and tight rock rhythm section: soaring French horns and trumpets, racing spiccato strings, punchy acoustic drums, electric bass and crisp rhythm guitar. Brass melody is memorable and singable, with a clear original eight-bar motif. Confident, playful, heroic competition in a huge copper-and-stone alchemical foundry lit by molten gold and teal lamps. Clean modern game soundtrack mix, articulate transients, controlled bass, room for combat sound effects. No vocals, choir, speech, ambient drones, music box, horror, chiptune, trailer risers or imitation of an existing song. CHARACTER SELECT AND REMATCH LOBBY. 126 BPM, F major, 4/4. Upbeat anticipation, compact heroic horn motif with playful string answers, tight bass groove, light rock drums and sparkling mallet accents. Medium intensity below battle music. Start with the groove immediately, give a clear memorable hook and a contrasting answer, return to the opening harmony. Continuous loop with no long intro, fade, ritardando or ending cadence. Feels like friends getting ready for the next round."
  },
  {
    "id": "arena-results",
    "url": "audio/music/arena/arena-results.mp3",
    "label": "A worthy challenger",
    "group": "Score · Arena",
    "role": "arena",
    "floor": null,
    "loop": false,
    "gaplessLoop": false,
    "key": "F major",
    "bpm": 156,
    "seconds": 12.04,
    "headSec": 0,
    "tailSec": 1.9,
    "lufs": -15.9,
    "bytes": 231799,
    "summary": "Original instrumental fantasy platform fighting game music. Live-sounding orchestra and tight rock rhythm section: soaring French horns and trumpets, racing spiccato strings, punchy acoustic drums, electric bass and crisp rhythm guitar. Brass melody is memorable and singable, with a clear original eight-bar motif. Confident, playful, heroic competition in a huge copper-and-stone alchemical foundry lit by molten gold and teal lamps. Clean modern game soundtrack mix, articulate transients, controlled bass, room for combat sound effects. No vocals, choir, speech, ambient drones, music box, horror, chiptune, trailer risers or imitation of an existing song. MATCH RESULTS VICTORY FANFARE, exactly 12 seconds. Start with an immediate joyful brass flourish and drum fill, state a short original heroic melody over bright major strings, then a proud satisfying full-orchestra final chord and a clean natural two-second reverb decay. Celebrates a good match between friends. No gloomy defeat motif. No spoken announcement. This is a short completed stinger, not a loop."
  }
];
