// GENERATED by scripts/audio/gen-duel-announcer.mjs — do not edit by hand.
// The Duel announcer's calls (content/audio/duelLines.ts), one mastered take each.

export const DUEL_ANNOUNCER_VOICE = {key:"david-shout",name:"David — sports arena announcer, [shouting]",model:"eleven_v3"} as const;

/** What the game needs at run time: line id → clip. */
export const DUEL_CLIPS: Readonly<Record<string, { readonly url: string; readonly seconds: number }>> = {
 choose: {
  url: "audio/duel/choose.mp3",
  seconds: 1.63
 },
 "fighter.ilyra-voss": {
  url: "audio/duel/fighter.ilyra-voss.mp3",
  seconds: 1.77
 },
 "fighter.brann-rook": {
  url: "audio/duel/fighter.brann-rook.mp3",
  seconds: 1.58
 },
 "fighter.sable-fen": {
  url: "audio/duel/fighter.sable-fen.mp3",
  seconds: 1.65
 },
 "fighter.mara-quell": {
  url: "audio/duel/fighter.mara-quell.mp3",
  seconds: 1.38
 },
 "fighter.kest-rel": {
  url: "audio/duel/fighter.kest-rel.mp3",
  seconds: 2.14
 },
 "fighter.nox-calder": {
  url: "audio/duel/fighter.nox-calder.mp3",
  seconds: 1.53
 },
 "fighter.edda-morrow": {
  url: "audio/duel/fighter.edda-morrow.mp3",
  seconds: 1.75
 },
 "fighter.selene-wraith": {
  url: "audio/duel/fighter.selene-wraith.mp3",
  seconds: 1.27
 },
 "fighter.rusk-emberjaw": {
  url: "audio/duel/fighter.rusk-emberjaw.mp3",
  seconds: 1.68
 },
 "fighter.father-thorne": {
  url: "audio/duel/fighter.father-thorne.mp3",
  seconds: 1.2
 },
 "stage.foundry": {
  url: "audio/duel/stage.foundry.mp3",
  seconds: 1.44
 },
 "stage.kiln": {
  url: "audio/duel/stage.kiln.mp3",
  seconds: 1.06
 },
 "stage.cistern": {
  url: "audio/duel/stage.cistern.mp3",
  seconds: 1.52
 },
 "stage.gallery": {
  url: "audio/duel/stage.gallery.mp3",
  seconds: 1.21
 },
 "ready.1": {
  url: "audio/duel/ready.1.mp3",
  seconds: 1.91
 },
 "ready.2": {
  url: "audio/duel/ready.2.mp3",
  seconds: 1.48
 },
 challenger: {
  url: "audio/duel/challenger.mp3",
  seconds: 2.17
 },
 "count.3": {
  url: "audio/duel/count.3.mp3",
  seconds: 0.79
 },
 "count.2": {
  url: "audio/duel/count.2.mp3",
  seconds: 0.55
 },
 "count.1": {
  url: "audio/duel/count.1.mp3",
  seconds: 0.52
 },
 fight: {
  url: "audio/duel/fight.mp3",
  seconds: 0.61
 },
 ko: {
  url: "audio/duel/ko.mp3",
  seconds: 1.35
 },
 "ring-out": {
  url: "audio/duel/ring-out.mp3",
  seconds: 1.01
 },
 "self-destruct": {
  url: "audio/duel/self-destruct.mp3",
  seconds: 1.28
 },
 "last-stock": {
  url: "audio/duel/last-stock.mp3",
  seconds: 1.21
 },
 "shield-break": {
  url: "audio/duel/shield-break.mp3",
  seconds: 1.05
 },
 time: {
  url: "audio/duel/time.mp3",
  seconds: 0.95
 },
 game: {
  url: "audio/duel/game.mp3",
  seconds: 1
 },
 "wins.ilyra-voss": {
  url: "audio/duel/wins.ilyra-voss.mp3",
  seconds: 2.06
 },
 "wins.brann-rook": {
  url: "audio/duel/wins.brann-rook.mp3",
  seconds: 1.84
 },
 "wins.sable-fen": {
  url: "audio/duel/wins.sable-fen.mp3",
  seconds: 1.58
 },
 "wins.mara-quell": {
  url: "audio/duel/wins.mara-quell.mp3",
  seconds: 1.93
 },
 "wins.kest-rel": {
  url: "audio/duel/wins.kest-rel.mp3",
  seconds: 2.05
 },
 "wins.nox-calder": {
  url: "audio/duel/wins.nox-calder.mp3",
  seconds: 1.56
 },
 "wins.edda-morrow": {
  url: "audio/duel/wins.edda-morrow.mp3",
  seconds: 2.04
 },
 "wins.selene-wraith": {
  url: "audio/duel/wins.selene-wraith.mp3",
  seconds: 1.52
 },
 "wins.rusk-emberjaw": {
  url: "audio/duel/wins.rusk-emberjaw.mp3",
  seconds: 1.52
 },
 "wins.father-thorne": {
  url: "audio/duel/wins.father-thorne.mp3",
  seconds: 1.38
 },
 draw: {
  url: "audio/duel/draw.mp3",
  seconds: 1.06
 },
 rematch: {
  url: "audio/duel/rematch.mp3",
  seconds: 0.84
 }
};

/** Every line with what speech-to-text heard in the shipped take (the audition page reads this). */
export const DUEL_CLIP_LINES: ReadonlyArray<{ readonly id: string; readonly text: string; readonly group: string; readonly heard: string; readonly confirmed: boolean }> = [
 {
  id: "choose",
  text: "Choose your fighter!",
  group: "select",
  heard: "Choose your fighter",
  confirmed: true
 },
 {
  id: "fighter.ilyra-voss",
  text: "Ilyra Voss!",
  group: "select",
  heard: "Illyra Voss",
  confirmed: true
 },
 {
  id: "fighter.brann-rook",
  text: "Brann Rook!",
  group: "select",
  heard: "Brian Rook",
  confirmed: true
 },
 {
  id: "fighter.sable-fen",
  text: "Sable Fen!",
  group: "select",
  heard: "Sable Fan",
  confirmed: true
 },
 {
  id: "fighter.mara-quell",
  text: "Mara Quell!",
  group: "select",
  heard: "Mara Quell",
  confirmed: true
 },
 {
  id: "fighter.kest-rel",
  text: "Kest Rel!",
  group: "select",
  heard: "KEST Rel",
  confirmed: true
 },
 {
  id: "fighter.nox-calder",
  text: "Nox Calder!",
  group: "select",
  heard: "Knox Calder",
  confirmed: true
 },
 {
  id: "fighter.edda-morrow",
  text: "Edda Morrow!",
  group: "select",
  heard: "Etta Morrow",
  confirmed: true
 },
 {
  id: "fighter.selene-wraith",
  text: "Selene Wraith!",
  group: "select",
  heard: "Celine Wraith",
  confirmed: true
 },
 {
  id: "fighter.rusk-emberjaw",
  text: "Rusk Emberjaw!",
  group: "select",
  heard: "Rusk Emberjaw",
  confirmed: true
 },
 {
  id: "fighter.father-thorne",
  text: "Father Thorne!",
  group: "select",
  heard: "Father Thorne!",
  confirmed: true
 },
 {
  id: "stage.foundry",
  text: "The Foundry!",
  group: "select",
  heard: "The Foundry",
  confirmed: true
 },
 {
  id: "stage.kiln",
  text: "The Kiln!",
  group: "select",
  heard: "The Kiln",
  confirmed: true
 },
 {
  id: "stage.cistern",
  text: "The Cistern!",
  group: "select",
  heard: "The cistern",
  confirmed: true
 },
 {
  id: "stage.gallery",
  text: "The Gallery!",
  group: "select",
  heard: "The gallery",
  confirmed: true
 },
 {
  id: "ready.1",
  text: "Player one, ready!",
  group: "select",
  heard: "Player one, ready",
  confirmed: true
 },
 {
  id: "ready.2",
  text: "Player two, ready!",
  group: "select",
  heard: "Player two, ready",
  confirmed: true
 },
 {
  id: "challenger",
  text: "Here comes a new challenger!",
  group: "select",
  heard: "Here comes a new challenger",
  confirmed: true
 },
 {
  id: "count.3",
  text: "Three!",
  group: "match",
  heard: "Three",
  confirmed: true
 },
 {
  id: "count.2",
  text: "Two!",
  group: "match",
  heard: "Two",
  confirmed: true
 },
 {
  id: "count.1",
  text: "One!",
  group: "match",
  heard: "One",
  confirmed: true
 },
 {
  id: "fight",
  text: "Fight!",
  group: "match",
  heard: "Fight",
  confirmed: true
 },
 {
  id: "ko",
  text: "K.O.!",
  group: "match",
  heard: "KO",
  confirmed: true
 },
 {
  id: "ring-out",
  text: "Ring out!",
  group: "match",
  heard: "Ring out",
  confirmed: true
 },
 {
  id: "self-destruct",
  text: "Self-destruct!",
  group: "match",
  heard: "Self-destruct",
  confirmed: true
 },
 {
  id: "last-stock",
  text: "Last stock!",
  group: "match",
  heard: "Last stock",
  confirmed: true
 },
 {
  id: "shield-break",
  text: "Shield break!",
  group: "match",
  heard: "Shield break",
  confirmed: true
 },
 {
  id: "time",
  text: "Time!",
  group: "result",
  heard: "Time!",
  confirmed: true
 },
 {
  id: "game",
  text: "Game!",
  group: "result",
  heard: "Game!",
  confirmed: true
 },
 {
  id: "wins.ilyra-voss",
  text: "Ilyra wins!",
  group: "result",
  heard: "Hilra wins",
  confirmed: true
 },
 {
  id: "wins.brann-rook",
  text: "Brann wins!",
  group: "result",
  heard: "Bran wins",
  confirmed: true
 },
 {
  id: "wins.sable-fen",
  text: "Sable wins!",
  group: "result",
  heard: "Sable wins",
  confirmed: true
 },
 {
  id: "wins.mara-quell",
  text: "Mara wins!",
  group: "result",
  heard: "Mara wins",
  confirmed: true
 },
 {
  id: "wins.kest-rel",
  text: "Kest wins!",
  group: "result",
  heard: "KEST wins",
  confirmed: true
 },
 {
  id: "wins.nox-calder",
  text: "Nox wins!",
  group: "result",
  heard: "Knox wins",
  confirmed: true
 },
 {
  id: "wins.edda-morrow",
  text: "Edda wins!",
  group: "result",
  heard: "Edda wins",
  confirmed: true
 },
 {
  id: "wins.selene-wraith",
  text: "Selene wins!",
  group: "result",
  heard: "Celine wins",
  confirmed: true
 },
 {
  id: "wins.rusk-emberjaw",
  text: "Rusk wins!",
  group: "result",
  heard: "Rusk wins",
  confirmed: true
 },
 {
  id: "wins.father-thorne",
  text: "Thorne wins!",
  group: "result",
  heard: "Thorn wins",
  confirmed: true
 },
 {
  id: "draw",
  text: "Draw game!",
  group: "result",
  heard: "Draw game",
  confirmed: true
 },
 {
  id: "rematch",
  text: "Rematch!",
  group: "result",
  heard: "Rematch",
  confirmed: true
 }
];

/** The casting (scripts/audio/duel-announcer-cast.json): every candidate read the same script; the audition page lists them. */
export const DUEL_ANNOUNCER_CAST: ReadonlyArray<{ readonly rank: number; readonly key: string; readonly name: string; readonly url: string; readonly seconds: number;
  readonly f0Median: number; readonly f0RangeSt: number; readonly presenceDb: number; readonly sibilantPerSecond: number; readonly heard: string; readonly excluded: string | null }> = [
 {
  rank: 1,
  key: "david-shout",
  name: "David — sports arena announcer, [shouting]",
  url: "audition/announcer/cast-david-shout.mp3",
  seconds: 11.69,
  f0Median: 172,
  f0RangeSt: 14.7,
  presenceDb: -1.7,
  sibilantPerSecond: 4.62,
  heard: "Choose your fighter. Selene Wraith. Three, two, one, fight. Here comes a new challenger. Last stock. Self-destruct. Game. Father Thorn wins",
  excluded: null
 },
 {
  rank: 2,
  key: "david",
  name: "David — sports arena announcer",
  url: "audition/announcer/cast-david.mp3",
  seconds: 12.79,
  f0Median: 205.1,
  f0RangeSt: 16.2,
  presenceDb: -2.4,
  sibilantPerSecond: 5.24,
  heard: "Choose your fighter. Selene Wraith. Three, two, one, fight. Here comes a new challenger. Last stock. Self-destruct. Game. Father Thorn wins",
  excluded: null
 },
 {
  rank: 3,
  key: "design-2",
  name: "Designed preview 2",
  url: "audition/announcer/design-2.mp3",
  seconds: 17.18,
  f0Median: 285.7,
  f0RangeSt: 11.6,
  presenceDb: 6.5,
  sibilantPerSecond: 3.38,
  heard: "Choose your fighter. Selene Wraith. Three, two, one. Fight. Here comes a new challenger. Last stock. Self-destruct. Game. Father Thorn wins",
  excluded: null
 },
 {
  rank: 4,
  key: "david-creative",
  name: "David — sports arena announcer, creative (stability 0)",
  url: "audition/announcer/cast-david-creative.mp3",
  seconds: 12.65,
  f0Median: 183.9,
  f0RangeSt: 11.7,
  presenceDb: -2.2,
  sibilantPerSecond: 5.85,
  heard: "Choose your fighter. Selene Wraith. Three, two, one, fight. Here comes a new challenger. Last stock. Self-destruct. Game. Father Thorn wins",
  excluded: null
 },
 {
  rank: 5,
  key: "grant",
  name: "Grant — hyper, over-the-top and loud",
  url: "audition/announcer/cast-grant.mp3",
  seconds: 10.56,
  f0Median: 320,
  f0RangeSt: 17,
  presenceDb: -4.7,
  sibilantPerSecond: 10.32,
  heard: "Choose your fighter. Selene Wraith. Three, two, one, fight. Here comes a new challenger. Last stock. Self-destruct. Game. Father Thorn wins",
  excluded: null
 },
 {
  rank: 6,
  key: "tyler",
  name: "Tyler — energetic arena announcer",
  url: "audition/announcer/cast-tyler.mp3",
  seconds: 13.6,
  f0Median: 158.4,
  f0RangeSt: 6.1,
  presenceDb: -0.6,
  sibilantPerSecond: 4.93,
  heard: "Choose your fighter. Selene Wraith. Three, two, one, fight. Here comes a new challenger. Last stock. Self-destruct. Game. Father Thorn wins",
  excluded: null
 },
 {
  rank: 7,
  key: "design-1",
  name: "Designed preview 1",
  url: "audition/announcer/design-1.mp3",
  seconds: 20.76,
  f0Median: 363.6,
  f0RangeSt: 11.1,
  presenceDb: 4.7,
  sibilantPerSecond: 4.67,
  heard: "Choose your fighter. Selene Wraith. Three, two, one, fight. Here comes a new challenger. Last stock. Self-destruct. Game. Father Thorn wins",
  excluded: null
 },
 {
  rank: 8,
  key: "ryan",
  name: "Ryan — event voice of god",
  url: "audition/announcer/cast-ryan.mp3",
  seconds: 13.46,
  f0Median: 166.7,
  f0RangeSt: 10.8,
  presenceDb: -7.8,
  sibilantPerSecond: 7.06,
  heard: "Choose your fighter. Selene Raith. Three, two, one, fight. Here comes a new challenger. Last stock. Self-destruct. Game. Father Thorn wins",
  excluded: null
 },
 {
  rank: 9,
  key: "design-3",
  name: "Designed preview 3",
  url: "audition/announcer/design-3.mp3",
  seconds: 19,
  f0Median: 340.4,
  f0RangeSt: 10.9,
  presenceDb: 1.8,
  sibilantPerSecond: 5.32,
  heard: "Choose your fighter. Selene Wraith. Three, two, one, fight. Here comes a new challenger. Last stock. Self-destruct. Game. Father Thord wins",
  excluded: null
 },
 {
  rank: 10,
  key: "jerry",
  name: "Jerry B. — announcer and broadcast voice",
  url: "audition/announcer/cast-jerry.mp3",
  seconds: 15.04,
  f0Median: 266.7,
  f0RangeSt: 13.6,
  presenceDb: -6.7,
  sibilantPerSecond: 6.12,
  heard: "Choose your fighter. Selene Wraith. Three, two, one, fight. Here comes a new challenger. Last stock. Self-destruct. Game. Father Thorn wins",
  excluded: null
 },
 {
  rank: 11,
  key: "xavier",
  name: "Xavier — dominating, metallic announcer",
  url: "audition/announcer/cast-xavier.mp3",
  seconds: 20.21,
  f0Median: 156.9,
  f0RangeSt: 20,
  presenceDb: -8.6,
  sibilantPerSecond: 4.85,
  heard: "Choose your fighter. Sameen, Rafe. Three, two, one. Fight. Here comes a new challenger. Last stock. Self-destruct. Game. Father Thorn wins",
  excluded: "misheard selene→sameen, wraith→rafe"
 }
];

export const DUEL_CAST_SCRIPT = "Choose your fighter! Selene Wraith! Three! Two! One! Fight! Here comes a new challenger! Last stock! Self-destruct! Game! Father Thorne wins!";
export const DUEL_CAST_RULE = "drop a candidate speech-to-text did not hear back word for word (an invented name within 60% of its spelling) or whose S sounds score under 60% of the field median; rank the rest by boom-and-hype = z(presence: vocal effort) + z(pitch range: a lively read) - z(median pitch: a booming register)";
