// GENERATED by scripts/audio/gen-voice.mjs — do not edit by hand.
// The narrator's clips, keyed by narrationKey(text) (src/audio/narrationText.ts).
import type { NarrationCandidate, NarrationClip, NarrationLine } from '@/content/audio/narrationTypes';

export const NARRATOR_VOICE = {key:"daniel",name:"Daniel — the gruff old British wizard",model:"eleven_v3"} as const;

/** The line every narrator candidate reads on the audition page. */
export const NARRATOR_SAMPLE = "The Bellows. The Works draw breath. Mind the pressure. And please, do mind the duck: it has been here longer than you have, and it knows where the tea is kept.";

/** What the game needs at run time: key → clip. */
export const NARRATION_CLIPS: Readonly<Record<string, NarrationClip>> = {
 "78213380": {
  url: "audio/voice/78213380.mp3",
  seconds: 4
 },
 "91830607": {
  url: "audio/voice/91830607.mp3",
  seconds: 3.44
 },
 "d486ea84": {
  url: "audio/voice/d486ea84.mp3",
  seconds: 9.02
 },
 "0b348985": {
  url: "audio/voice/0b348985.mp3",
  seconds: 7.12
 },
 "0385d169": {
  url: "audio/voice/0385d169.mp3",
  seconds: 7.28
 },
 "f038efe5": {
  url: "audio/voice/f038efe5.mp3",
  seconds: 8.32
 },
 "ba957668": {
  url: "audio/voice/ba957668.mp3",
  seconds: 7.61
 },
 "0c1c54c1": {
  url: "audio/voice/0c1c54c1.mp3",
  seconds: 8.48
 },
 "5e82323f": {
  url: "audio/voice/5e82323f.mp3",
  seconds: 7.84
 },
 "4832ad5f": {
  url: "audio/voice/4832ad5f.mp3",
  seconds: 6.69
 },
 "60a5e047": {
  url: "audio/voice/60a5e047.mp3",
  seconds: 4.75,
  captioned: true
 },
 "cbc141aa": {
  url: "audio/voice/cbc141aa.mp3",
  seconds: 4.03,
  captioned: true
 },
 "461853b2": {
  url: "audio/voice/461853b2.mp3",
  seconds: 2.45
 },
 "9c378255": {
  url: "audio/voice/9c378255.mp3",
  seconds: 2.8
 },
 "2a03f631": {
  url: "audio/voice/2a03f631.mp3",
  seconds: 2.16
 },
 "d11f0fa0": {
  url: "audio/voice/d11f0fa0.mp3",
  seconds: 1.84
 },
 "b67e3823": {
  url: "audio/voice/b67e3823.mp3",
  seconds: 1.58
 },
 "1ad0a89c": {
  url: "audio/voice/1ad0a89c.mp3",
  seconds: 0.64
 },
 "d440ddfa": {
  url: "audio/voice/d440ddfa.mp3",
  seconds: 1.2
 },
 "f46aa2aa": {
  url: "audio/voice/f46aa2aa.mp3",
  seconds: 3.04
 },
 "5c2a1e51": {
  url: "audio/voice/5c2a1e51.mp3",
  seconds: 1.67
 },
 "2d36a7dc": {
  url: "audio/voice/2d36a7dc.mp3",
  seconds: 1.68
 },
 "0468773a": {
  url: "audio/voice/0468773a.mp3",
  seconds: 1.84
 },
 "fb96edf3": {
  url: "audio/voice/fb96edf3.mp3",
  seconds: 1.92
 },
 "9997e670": {
  url: "audio/voice/9997e670.mp3",
  seconds: 1.68
 },
 "5ac70782": {
  url: "audio/voice/5ac70782.mp3",
  seconds: 1.52
 },
 "112a2c89": {
  url: "audio/voice/112a2c89.mp3",
  seconds: 3.36
 },
 "4ef597c5": {
  url: "audio/voice/4ef597c5.mp3",
  seconds: 1.6
 },
 "7d4e76b7": {
  url: "audio/voice/7d4e76b7.mp3",
  seconds: 2.05
 },
 "4f1dafb9": {
  url: "audio/voice/4f1dafb9.mp3",
  seconds: 3.16
 },
 "bf79a725": {
  url: "audio/voice/bf79a725.mp3",
  seconds: 1.6
 },
 "9b9a14d8": {
  url: "audio/voice/9b9a14d8.mp3",
  seconds: 2.11
 },
 "c8f4bc24": {
  url: "audio/voice/c8f4bc24.mp3",
  seconds: 2.88
 },
 "b0d344fd": {
  url: "audio/voice/b0d344fd.mp3",
  seconds: 2.08
 },
 "d39e9e91": {
  url: "audio/voice/d39e9e91.mp3",
  seconds: 2.16
 },
 "007ca4f4": {
  url: "audio/voice/007ca4f4.mp3",
  seconds: 3.2
 },
 "eaa2ff43": {
  url: "audio/voice/eaa2ff43.mp3",
  seconds: 5.36
 },
 "4e2d8eab": {
  url: "audio/voice/4e2d8eab.mp3",
  seconds: 4.77
 },
 "52bbf8e1": {
  url: "audio/voice/52bbf8e1.mp3",
  seconds: 3.12
 },
 "6d5db4eb": {
  url: "audio/voice/6d5db4eb.mp3",
  seconds: 4.74
 },
 "fc7683eb": {
  url: "audio/voice/fc7683eb.mp3",
  seconds: 2.16
 },
 "11ec726f": {
  url: "audio/voice/11ec726f.mp3",
  seconds: 2.67
 },
 "3f36a2d2": {
  url: "audio/voice/3f36a2d2.mp3",
  seconds: 3.6
 },
 "fb37b9f7": {
  url: "audio/voice/fb37b9f7.mp3",
  seconds: 2.79
 },
 "fc526d8a": {
  url: "audio/voice/fc526d8a.mp3",
  seconds: 2.16
 },
 "7bd0939f": {
  url: "audio/voice/7bd0939f.mp3",
  seconds: 3.44
 },
 "744022af": {
  url: "audio/voice/744022af.mp3",
  seconds: 2.88
 },
 "1ee5e288": {
  url: "audio/voice/1ee5e288.mp3",
  seconds: 5.6
 },
 "ffccc90d": {
  url: "audio/voice/ffccc90d.mp3",
  seconds: 4
 },
 "2b1d0f6a": {
  url: "audio/voice/2b1d0f6a.mp3",
  seconds: 4.48
 },
 "852840d9": {
  url: "audio/voice/852840d9.mp3",
  seconds: 1.19
 },
 "568f0e13": {
  url: "audio/voice/568f0e13.mp3",
  seconds: 4.49
 },
 "97a0070a": {
  url: "audio/voice/97a0070a.mp3",
  seconds: 3.68
 },
 "2bdc9400": {
  url: "audio/voice/2bdc9400.mp3",
  seconds: 4.16
 },
 "f4217730": {
  url: "audio/voice/f4217730.mp3",
  seconds: 2.48
 },
 "9a7be7c3": {
  url: "audio/voice/9a7be7c3.mp3",
  seconds: 3.48
 },
 "ae74033a": {
  url: "audio/voice/ae74033a.mp3",
  seconds: 5.37
 },
 "28442cb1": {
  url: "audio/voice/28442cb1.mp3",
  seconds: 1.68
 },
 "bb56a48b": {
  url: "audio/voice/bb56a48b.mp3",
  seconds: 3.42
 },
 "5693dc11": {
  url: "audio/voice/5693dc11.mp3",
  seconds: 3.84
 },
 "43a3a108": {
  url: "audio/voice/43a3a108.mp3",
  seconds: 1.2
 },
 "689bee0b": {
  url: "audio/voice/689bee0b.mp3",
  seconds: 3.81
 },
 "02e8d016": {
  url: "audio/voice/02e8d016.mp3",
  seconds: 3.12
 },
 "9b9e86d3": {
  url: "audio/voice/9b9e86d3.mp3",
  seconds: 5.6
 },
 "32b02cc3": {
  url: "audio/voice/32b02cc3.mp3",
  seconds: 2.32
 },
 "67f26592": {
  url: "audio/voice/67f26592.mp3",
  seconds: 0.82
 },
 "fa5e86f2": {
  url: "audio/voice/fa5e86f2.mp3",
  seconds: 3.2
 },
 "149140d7": {
  url: "audio/voice/149140d7.mp3",
  seconds: 4.39
 },
 "8bf5a6af": {
  url: "audio/voice/8bf5a6af.mp3",
  seconds: 3.66
 },
 "6adc69ed": {
  url: "audio/voice/6adc69ed.mp3",
  seconds: 3.75
 },
 "834a9b53": {
  url: "audio/voice/834a9b53.mp3",
  seconds: 2.72
 },
 "722268d3": {
  url: "audio/voice/722268d3.mp3",
  seconds: 1.28
 },
 "ca7a90e2": {
  url: "audio/voice/ca7a90e2.mp3",
  seconds: 2.59
 },
 "8e281ebb": {
  url: "audio/voice/8e281ebb.mp3",
  seconds: 3.07
 },
 "de99388e": {
  url: "audio/voice/de99388e.mp3",
  seconds: 3.39
 },
 "1120618b": {
  url: "audio/voice/1120618b.mp3",
  seconds: 3.12
 },
 "4c6e719f": {
  url: "audio/voice/4c6e719f.mp3",
  seconds: 4.8
 },
 "eb27caa7": {
  url: "audio/voice/eb27caa7.mp3",
  seconds: 2.8
 },
 "a2a070a7": {
  url: "audio/voice/a2a070a7.mp3",
  seconds: 1.36
 },
 "95f8ec08": {
  url: "audio/voice/95f8ec08.mp3",
  seconds: 4.28
 },
 "1ecc8201": {
  url: "audio/voice/1ecc8201.mp3",
  seconds: 3.68
 },
 "e5113309": {
  url: "audio/voice/e5113309.mp3",
  seconds: 2.78
 },
 "3ee85252": {
  url: "audio/voice/3ee85252.mp3",
  seconds: 2.72
 },
 "c3162e5f": {
  url: "audio/voice/c3162e5f.mp3",
  seconds: 1.28
 },
 "b0a8ad39": {
  url: "audio/voice/b0a8ad39.mp3",
  seconds: 4.83
 },
 "238fd6b4": {
  url: "audio/voice/238fd6b4.mp3",
  seconds: 5.82
 },
 "47c8959e": {
  url: "audio/voice/47c8959e.mp3",
  seconds: 4.24
 },
 "f5efe778": {
  url: "audio/voice/f5efe778.mp3",
  seconds: 2.56
 },
 "3709450e": {
  url: "audio/voice/3709450e.mp3",
  seconds: 0.88
 },
 "5c4641dc": {
  url: "audio/voice/5c4641dc.mp3",
  seconds: 3.2
 },
 "a61d7e08": {
  url: "audio/voice/a61d7e08.mp3",
  seconds: 3.36
 },
 "ffd20377": {
  url: "audio/voice/ffd20377.mp3",
  seconds: 3.54
 },
 "75b4a9c6": {
  url: "audio/voice/75b4a9c6.mp3",
  seconds: 3.76
 },
 "6ddd62a9": {
  url: "audio/voice/6ddd62a9.mp3",
  seconds: 2.72
 },
 "79a825b5": {
  url: "audio/voice/79a825b5.mp3",
  seconds: 2.64
 },
 "c9cd4701": {
  url: "audio/voice/c9cd4701.mp3",
  seconds: 2.8
 },
 "b445fa69": {
  url: "audio/voice/b445fa69.mp3",
  seconds: 2.08
 },
 "b9f7c08a": {
  url: "audio/voice/b9f7c08a.mp3",
  seconds: 3.44
 },
 "29f45618": {
  url: "audio/voice/29f45618.mp3",
  seconds: 2.96
 },
 "79c416ad": {
  url: "audio/voice/79c416ad.mp3",
  seconds: 4.24
 },
 "137c9934": {
  url: "audio/voice/137c9934.mp3",
  seconds: 7.44
 },
 "2f3e7705": {
  url: "audio/voice/2f3e7705.mp3",
  seconds: 0.88
 },
 "16f819bf": {
  url: "audio/voice/16f819bf.mp3",
  seconds: 3.76
 },
 "dad3dc72": {
  url: "audio/voice/dad3dc72.mp3",
  seconds: 2.32
 },
 "f5c4bf47": {
  url: "audio/voice/f5c4bf47.mp3",
  seconds: 1.04
 },
 "f2dfbea6": {
  url: "audio/voice/f2dfbea6.mp3",
  seconds: 4.48
 },
 "af8f3a57": {
  url: "audio/voice/af8f3a57.mp3",
  seconds: 2.85
 },
 "5952ac38": {
  url: "audio/voice/5952ac38.mp3",
  seconds: 1.28
 },
 "c5de5ef6": {
  url: "audio/voice/c5de5ef6.mp3",
  seconds: 4.88
 },
 "3ca3110e": {
  url: "audio/voice/3ca3110e.mp3",
  seconds: 4.18
 },
 "30486fc1": {
  url: "audio/voice/30486fc1.mp3",
  seconds: 3.19
 },
 "f325bbf1": {
  url: "audio/voice/f325bbf1.mp3",
  seconds: 2.23
 },
 "3205a1d9": {
  url: "audio/voice/3205a1d9.mp3",
  seconds: 4.26
 },
 "ced1f053": {
  url: "audio/voice/ced1f053.mp3",
  seconds: 3.28
 },
 "e8071e34": {
  url: "audio/voice/e8071e34.mp3",
  seconds: 1.76
 },
 "f85bf22c": {
  url: "audio/voice/f85bf22c.mp3",
  seconds: 4.48
 },
 "f001ebff": {
  url: "audio/voice/f001ebff.mp3",
  seconds: 2
 },
 "e19779e7": {
  url: "audio/voice/e19779e7.mp3",
  seconds: 2.64
 },
 "b79860b2": {
  url: "audio/voice/b79860b2.mp3",
  seconds: 2.83
 },
 "a24c7037": {
  url: "audio/voice/a24c7037.mp3",
  seconds: 1.28
 },
 "ef6d4989": {
  url: "audio/voice/ef6d4989.mp3",
  seconds: 2.72
 },
 "469e5646": {
  url: "audio/voice/469e5646.mp3",
  seconds: 4.96
 },
 "846d7bfa": {
  url: "audio/voice/846d7bfa.mp3",
  seconds: 2.88
 },
 "a24fe67f": {
  url: "audio/voice/a24fe67f.mp3",
  seconds: 3.35
 },
 "67b6d2a5": {
  url: "audio/voice/67b6d2a5.mp3",
  seconds: 4.8
 },
 "834b7a28": {
  url: "audio/voice/834b7a28.mp3",
  seconds: 3.03
 },
 "85fcb302": {
  url: "audio/voice/85fcb302.mp3",
  seconds: 2.15
 },
 "d992dcb1": {
  url: "audio/voice/d992dcb1.mp3",
  seconds: 3.84
 },
 "84b0b82c": {
  url: "audio/voice/84b0b82c.mp3",
  seconds: 4.08
 },
 "021173e9": {
  url: "audio/voice/021173e9.mp3",
  seconds: 1.95
 },
 "b4d1c838": {
  url: "audio/voice/b4d1c838.mp3",
  seconds: 3.08
 },
 "639f5bb5": {
  url: "audio/voice/639f5bb5.mp3",
  seconds: 1.92
 },
 "88d0dea0": {
  url: "audio/voice/88d0dea0.mp3",
  seconds: 4.96
 },
 "bd5b6740": {
  url: "audio/voice/bd5b6740.mp3",
  seconds: 2.4
 },
 "4db18cb0": {
  url: "audio/voice/4db18cb0.mp3",
  seconds: 3.2
 },
 "93ac4a43": {
  url: "audio/voice/93ac4a43.mp3",
  seconds: 5.2
 },
 "a6931200": {
  url: "audio/voice/a6931200.mp3",
  seconds: 4.81
 },
 "9d0914d1": {
  url: "audio/voice/9d0914d1.mp3",
  seconds: 5.28
 },
 "6e675487": {
  url: "audio/voice/6e675487.mp3",
  seconds: 1.28
 },
 "ee03f586": {
  url: "audio/voice/ee03f586.mp3",
  seconds: 2.59
 },
 "d8b31898": {
  url: "audio/voice/d8b31898.mp3",
  seconds: 2.47
 },
 "010ab859": {
  url: "audio/voice/010ab859.mp3",
  seconds: 1.46
 },
 "1687f393": {
  url: "audio/voice/1687f393.mp3",
  seconds: 4.4
 },
 "1ae676dc": {
  url: "audio/voice/1ae676dc.mp3",
  seconds: 2
 },
 "42e037b9": {
  url: "audio/voice/42e037b9.mp3",
  seconds: 6.16
 },
 "0dd7b5f3": {
  url: "audio/voice/0dd7b5f3.mp3",
  seconds: 3.2
 },
 "4b9d5a04": {
  url: "audio/voice/4b9d5a04.mp3",
  seconds: 1.28
 },
 "6ed85358": {
  url: "audio/voice/6ed85358.mp3",
  seconds: 1.76
 },
 "f6d7b040": {
  url: "audio/voice/f6d7b040.mp3",
  seconds: 2.32
 },
 "b64497dc": {
  url: "audio/voice/b64497dc.mp3",
  seconds: 1.2
 },
 "9ddb206f": {
  url: "audio/voice/9ddb206f.mp3",
  seconds: 4.56
 },
 "f58f9195": {
  url: "audio/voice/f58f9195.mp3",
  seconds: 3.28
 },
 "a9888d37": {
  url: "audio/voice/a9888d37.mp3",
  seconds: 3.15
 },
 "c03e88b4": {
  url: "audio/voice/c03e88b4.mp3",
  seconds: 2.43
 },
 "1967d415": {
  url: "audio/voice/1967d415.mp3",
  seconds: 2.93
 },
 "6a025a89": {
  url: "audio/voice/6a025a89.mp3",
  seconds: 4.07
 },
 "f2a19a95": {
  url: "audio/voice/f2a19a95.mp3",
  seconds: 1.36
 },
 "7abc81bf": {
  url: "audio/voice/7abc81bf.mp3",
  seconds: 4.24
 },
 "c3bc2233": {
  url: "audio/voice/c3bc2233.mp3",
  seconds: 2.4
 },
 "cfa9b63e": {
  url: "audio/voice/cfa9b63e.mp3",
  seconds: 6.8
 },
 "7772e8f7": {
  url: "audio/voice/7772e8f7.mp3",
  seconds: 3.84
 },
 "e106828c": {
  url: "audio/voice/e106828c.mp3",
  seconds: 1.63
 },
 "b17079ec": {
  url: "audio/voice/b17079ec.mp3",
  seconds: 7.76
 },
 "1380ece7": {
  url: "audio/voice/1380ece7.mp3",
  seconds: 1.98
 },
 "611c3d75": {
  url: "audio/voice/611c3d75.mp3",
  seconds: 2.02
 },
 "7204eb8a": {
  url: "audio/voice/7204eb8a.mp3",
  seconds: 1.92
 },
 "344e1388": {
  url: "audio/voice/344e1388.mp3",
  seconds: 2.16
 },
 "8b69f07b": {
  url: "audio/voice/8b69f07b.mp3",
  seconds: 2.64
 },
 "1a038953": {
  url: "audio/voice/1a038953.mp3",
  seconds: 2.64
 },
 "51bdf1b7": {
  url: "audio/voice/51bdf1b7.mp3",
  seconds: 1.92
 },
 "0437bddb": {
  url: "audio/voice/0437bddb.mp3",
  seconds: 2.08
 },
 "5a3bb28f": {
  url: "audio/voice/5a3bb28f.mp3",
  seconds: 5.12
 },
 "46e1fe93": {
  url: "audio/voice/46e1fe93.mp3",
  seconds: 3.31
 },
 "01a58998": {
  url: "audio/voice/01a58998.mp3",
  seconds: 2.56
 },
 "ed0c2fec": {
  url: "audio/voice/ed0c2fec.mp3",
  seconds: 6.63
 },
 "3698d668": {
  url: "audio/voice/3698d668.mp3",
  seconds: 6.4
 },
 "6ac75f06": {
  url: "audio/voice/6ac75f06.mp3",
  seconds: 6.48
 },
 "eeda0140": {
  url: "audio/voice/eeda0140.mp3",
  seconds: 5.36,
  captioned: true
 }
};

/** Every line with its text, for the audition page (the game never reads this). */
export const NARRATION_LINES: readonly NarrationLine[] = [
 {
  key: "d486ea84",
  text: "Something is alive in the old refinery. Listen. Experiment. Find your way down.",
  say: "[softly] Something is alive in the old refinery. Listen. Experiment. Find your way down.",
  group: "Title",
  seconds: 9.02,
  urls: [
   "audio/voice/d486ea84.mp3",
   "audio/voice/d486ea84-2.mp3"
  ]
 },
 {
  key: "0b348985",
  text: "The Bellows. The Works draw breath. Mind the pressure.",
  say: "The Bellows. The Works draw breath. Mind the pressure.",
  group: "Floor arrivals",
  seconds: 7.12,
  urls: [
   "audio/voice/0b348985.mp3",
   "audio/voice/0b348985-2.mp3"
  ]
 },
 {
  key: "0385d169",
  text: "The Rot Gardens. Where the refinery digests. Do not linger.",
  say: "The Rot Gardens. Where the refinery digests. Do not linger.",
  group: "Floor arrivals",
  seconds: 7.28,
  urls: [
   "audio/voice/0385d169.mp3",
   "audio/voice/0385d169-2.mp3"
  ]
 },
 {
  key: "f038efe5",
  text: "The Drowned Cisterns. The veins run cold. Something large keeps them company.",
  say: "The Drowned Cisterns. The veins run cold. Something large keeps them company.",
  group: "Floor arrivals",
  seconds: 8.32,
  urls: [
   "audio/voice/f038efe5.mp3",
   "audio/voice/f038efe5-2.mp3"
  ]
 },
 {
  key: "ba957668",
  text: "The Kiln Heart. The heart still burns. It would rather you did not.",
  say: "The Kiln Heart. The heart still burns. It would rather you did not.",
  group: "Floor arrivals",
  seconds: 7.61,
  urls: [
   "audio/voice/ba957668.mp3",
   "audio/voice/ba957668-2.mp3"
  ]
 },
 {
  key: "0c1c54c1",
  text: "The gut. Everything here is growing, rotting, or making up its mind, and the air is flammable.",
  say: "The gut. Everything here is growing, rotting, or making up its mind, and the air is flammable.",
  group: "Sanctum",
  seconds: 8.48,
  urls: [
   "audio/voice/0c1c54c1.mp3"
  ]
 },
 {
  key: "5e82323f",
  text: "The veins. Several hundred tons of water and one very large tenant who never pays rent.",
  say: "The veins. Several hundred tons of water and one very large tenant who never pays rent.",
  group: "Sanctum",
  seconds: 7.84,
  urls: [
   "audio/voice/5e82323f.mp3"
  ]
 },
 {
  key: "4832ad5f",
  text: "The heart. Hot, loud, and under the impression that it is a volcano.",
  say: "The heart. Hot, loud, and under the impression that it is a volcano.",
  group: "Sanctum",
  seconds: 6.69,
  urls: [
   "audio/voice/4832ad5f.mp3"
  ]
 },
 {
  key: "60a5e047",
  text: "The Sunken Leviathan. It drains poorly.",
  say: "[whispers] The Sunken Leviathan. It drains poorly.",
  group: "Bosses · leviathan",
  seconds: 4.75,
  urls: [
   "audio/voice/60a5e047.mp3"
  ]
 },
 {
  key: "cbc141aa",
  text: "The Kiln Colossus. Stopping it is the whole point.",
  say: "The Kiln Colossus. Stopping it is the whole point.",
  group: "Bosses · colossus",
  seconds: 4.03,
  urls: [
   "audio/voice/cbc141aa.mp3"
  ]
 },
 {
  key: "461853b2",
  text: "Drain the Sunken Leviathan.",
  say: "Drain the Sunken Leviathan.",
  group: "Bosses",
  seconds: 2.45,
  urls: [
   "audio/voice/461853b2.mp3"
  ]
 },
 {
  key: "9c378255",
  text: "Bring down the Kiln Colossus.",
  say: "Bring down the Kiln Colossus.",
  group: "Bosses",
  seconds: 2.8,
  urls: [
   "audio/voice/9c378255.mp3"
  ]
 },
 {
  key: "2a03f631",
  text: "THE SUMP FALLS STILL",
  say: "The sump falls still.",
  group: "Bosses",
  seconds: 2.16,
  urls: [
   "audio/voice/2a03f631.mp3"
  ]
 },
 {
  key: "d11f0fa0",
  text: "THE KILN IS COLD",
  say: "The kiln is cold.",
  group: "Bosses",
  seconds: 1.84,
  urls: [
   "audio/voice/d11f0fa0.mp3"
  ]
 },
 {
  key: "b67e3823",
  text: "THE CORE IS BARE",
  say: "The core is bare.",
  group: "Bosses · phases",
  seconds: 1.58,
  urls: [
   "audio/voice/b67e3823.mp3"
  ]
 },
 {
  key: "1ad0a89c",
  text: "SHORTED",
  say: "Shorted.",
  group: "Bosses · phases",
  seconds: 0.64,
  urls: [
   "audio/voice/1ad0a89c.mp3"
  ]
 },
 {
  key: "d440ddfa",
  text: "THERMAL SHOCK",
  say: "Thermal shock.",
  group: "Bosses · phases",
  seconds: 1.2,
  urls: [
   "audio/voice/d440ddfa.mp3"
  ]
 },
 {
  key: "f46aa2aa",
  text: "The Unreasonable Bell & Tea Engine",
  say: "The Unreasonable Bell and Tea Engine.",
  group: "Tea Engine · acts",
  seconds: 3.04,
  urls: [
   "audio/voice/f46aa2aa.mp3"
  ]
 },
 {
  key: "5c2a1e51",
  text: "First, a little powder",
  say: "First, a little powder.",
  group: "Tea Engine · acts",
  seconds: 1.67,
  urls: [
   "audio/voice/5c2a1e51.mp3"
  ]
 },
 {
  key: "2d36a7dc",
  text: "A broken coupling",
  say: "A broken coupling.",
  group: "Tea Engine · acts",
  seconds: 1.68,
  urls: [
   "audio/voice/2d36a7dc.mp3"
  ]
 },
 {
  key: "0468773a",
  text: "The knot is the fuse",
  say: "The knot is the fuse.",
  group: "Tea Engine · acts",
  seconds: 1.84,
  urls: [
   "audio/voice/0468773a.mp3"
  ]
 },
 {
  key: "fb96edf3",
  text: "Percussive maintenance",
  say: "Percussive maintenance.",
  group: "Tea Engine · acts",
  seconds: 1.92,
  urls: [
   "audio/voice/fb96edf3.mp3"
  ]
 },
 {
  key: "9997e670",
  text: "Downhill, briskly",
  say: "Downhill, briskly.",
  group: "Tea Engine · acts",
  seconds: 1.68,
  urls: [
   "audio/voice/9997e670.mp3"
  ]
 },
 {
  key: "5ac70782",
  text: "The tollgate is stuck",
  say: "The tollgate is stuck.",
  group: "Tea Engine · acts",
  seconds: 1.52,
  urls: [
   "audio/voice/5ac70782.mp3"
  ]
 },
 {
  key: "112a2c89",
  text: "Six dominoes and a wound spring",
  say: "Six dominoes and a wound spring.",
  group: "Tea Engine · acts",
  seconds: 3.36,
  urls: [
   "audio/voice/112a2c89.mp3"
  ]
 },
 {
  key: "4ef597c5",
  text: "The spring lets go",
  say: "The spring lets go.",
  group: "Tea Engine · acts",
  seconds: 1.6,
  urls: [
   "audio/voice/4ef597c5.mp3"
  ]
 },
 {
  key: "7d4e76b7",
  text: "Please mind the duck",
  say: "[dryly] Please mind the duck.",
  group: "Tea Engine · acts",
  seconds: 2.05,
  urls: [
   "audio/voice/7d4e76b7.mp3"
  ]
 },
 {
  key: "4f1dafb9",
  text: "A marble of some urgency",
  say: "A marble of some urgency.",
  group: "Tea Engine · acts",
  seconds: 3.16,
  urls: [
   "audio/voice/4f1dafb9.mp3"
  ]
 },
 {
  key: "bf79a725",
  text: "The second fuse",
  say: "The second fuse.",
  group: "Tea Engine · acts",
  seconds: 1.6,
  urls: [
   "audio/voice/bf79a725.mp3"
  ]
 },
 {
  key: "9b9a14d8",
  text: "This is probably enough heat",
  say: "[dryly] This is probably enough heat.",
  group: "Tea Engine · acts",
  seconds: 2.11,
  urls: [
   "audio/voice/9b9a14d8.mp3"
  ]
 },
 {
  key: "c8f4bc24",
  text: "A most electrifying tea bag",
  say: "A most electrifying tea bag.",
  group: "Tea Engine · acts",
  seconds: 2.88,
  urls: [
   "audio/voice/c8f4bc24.mp3"
  ]
 },
 {
  key: "b0d344fd",
  text: "The magnet has opinions",
  say: "The magnet has opinions.",
  group: "Tea Engine · acts",
  seconds: 2.08,
  urls: [
   "audio/voice/b0d344fd.mp3"
  ]
 },
 {
  key: "d39e9e91",
  text: "Gravity gets the last word",
  say: "Gravity gets the last word.",
  group: "Tea Engine · acts",
  seconds: 2.16,
  urls: [
   "audio/voice/d39e9e91.mp3"
  ]
 },
 {
  key: "007ca4f4",
  text: "Tea is served. The bell is yours.",
  say: "Tea is served. The bell is yours.",
  group: "Tea Engine · acts",
  seconds: 3.2,
  urls: [
   "audio/voice/007ca4f4.mp3"
  ]
 },
 {
  key: "eaa2ff43",
  text: "The descent gate needs its brass bell. Pull the crank to begin.",
  say: "The descent gate needs its brass bell. Pull the crank to begin.",
  group: "Tea Engine · acts",
  seconds: 5.36,
  urls: [
   "audio/voice/eaa2ff43.mp3"
  ]
 },
 {
  key: "4e2d8eab",
  text: "Collect the brass bell at the receiver, then carry it to the descent gate.",
  say: "Collect the brass bell at the receiver, then carry it to the descent gate.",
  group: "Tea Engine · acts",
  seconds: 4.77,
  urls: [
   "audio/voice/4e2d8eab.mp3"
  ]
 },
 {
  key: "52bbf8e1",
  text: "A slight technical difficulty",
  say: "[sighs] A slight technical difficulty.",
  group: "Tea Engine · faults",
  seconds: 3.12,
  urls: [
   "audio/voice/52bbf8e1.mp3"
  ]
 },
 {
  key: "6d5db4eb",
  text: "Return to the crank. Press Use to recharge the engine.",
  say: "Return to the crank. Press Use to recharge the engine.",
  group: "Tea Engine · faults",
  seconds: 4.74,
  urls: [
   "audio/voice/6d5db4eb.mp3"
  ]
 },
 {
  key: "fc7683eb",
  text: "Shoot the priming pan under the floor",
  say: "Shoot the priming pan under the floor.",
  group: "Tea Engine · faults",
  seconds: 2.16,
  urls: [
   "audio/voice/fc7683eb.mp3"
  ]
 },
 {
  key: "11ec726f",
  text: "Kick the Persuader hanging from the ceiling",
  say: "Kick the Persuader hanging from the ceiling.",
  group: "Tea Engine · faults",
  seconds: 2.67,
  urls: [
   "audio/voice/11ec726f.mp3"
  ]
 },
 {
  key: "3f36a2d2",
  text: "Pour water through the grate into the duck’s bath",
  say: "Pour water through the grate into the duck’s bath.",
  group: "Tea Engine · faults",
  seconds: 3.6,
  urls: [
   "audio/voice/3f36a2d2.mp3"
  ]
 },
 {
  key: "fb37b9f7",
  text: "The slow match reaches the priming pan.",
  say: "The slow match reaches the priming pan.",
  group: "Tea Engine · toasts",
  seconds: 2.79,
  urls: [
   "audio/voice/fb37b9f7.mp3"
  ]
 },
 {
  key: "fc526d8a",
  text: "The percussion cap fires.",
  say: "The percussion cap fires.",
  group: "Tea Engine · toasts",
  seconds: 2.16,
  urls: [
   "audio/voice/fc526d8a.mp3"
  ]
 },
 {
  key: "7bd0939f",
  text: "Engine recharged. Pull the crank to try again.",
  say: "Engine recharged. Pull the crank to try again.",
  group: "Tea Engine · toasts",
  seconds: 3.44,
  urls: [
   "audio/voice/7bd0939f.mp3"
  ]
 },
 {
  key: "744022af",
  text: "The clockwork knocker gives the Persuader a whack.",
  say: "The clockwork knocker gives the Persuader a whack.",
  group: "Tea Engine · toasts",
  seconds: 2.88,
  urls: [
   "audio/voice/744022af.mp3"
  ]
 },
 {
  key: "1ee5e288",
  text: "Bell & Tea Engine: The fuse fizzled out at the cracked coupling.",
  say: "Bell and Tea Engine: The fuse fizzled out at the cracked coupling.",
  group: "Tea Engine · toasts",
  seconds: 5.6,
  urls: [
   "audio/voice/1ee5e288.mp3"
  ]
 },
 {
  key: "ffccc90d",
  text: "Bell & Tea Engine: The tollgate is jammed shut.",
  say: "Bell and Tea Engine: The tollgate is jammed shut.",
  group: "Tea Engine · toasts",
  seconds: 4,
  urls: [
   "audio/voice/ffccc90d.mp3"
  ]
 },
 {
  key: "2b1d0f6a",
  text: "Bell & Tea Engine: The downpipe is clogged.",
  say: "Bell and Tea Engine: The downpipe is clogged.",
  group: "Tea Engine · toasts",
  seconds: 4.48,
  urls: [
   "audio/voice/2b1d0f6a.mp3"
  ]
 },
 {
  key: "852840d9",
  text: "You dissolved.",
  say: "You dissolved.",
  group: "Death · titles",
  seconds: 1.19,
  urls: [
   "audio/voice/852840d9.mp3"
  ]
 },
 {
  key: "568f0e13",
  text: "Dissolved by acid. Very clean work, chemically speaking.",
  say: "Dissolved by acid. Very clean work, chemically speaking.",
  group: "Death · causes",
  seconds: 4.49,
  urls: [
   "audio/voice/568f0e13.mp3"
  ]
 },
 {
  key: "97a0070a",
  text: "Acid reduced the alchemist to a smaller argument.",
  say: "Acid reduced the alchemist to a smaller argument.",
  group: "Death · causes",
  seconds: 3.68,
  urls: [
   "audio/voice/97a0070a.mp3"
  ]
 },
 {
  key: "2bdc9400",
  text: "Tagged by an acid glob. The glob was smug about it.",
  say: "[dryly] Tagged by an acid glob. The glob was smug about it.",
  group: "Death · causes",
  seconds: 4.16,
  urls: [
   "audio/voice/2bdc9400.mp3"
  ]
 },
 {
  key: "f4217730",
  text: "A caustic lob made its point.",
  say: "A caustic lob made its point.",
  group: "Death · causes",
  seconds: 2.48,
  urls: [
   "audio/voice/f4217730.mp3"
  ]
 },
 {
  key: "9a7be7c3",
  text: "An acid slime turned a hug into a hazard.",
  say: "An acid slime turned a hug into a hazard.",
  group: "Death · causes",
  seconds: 3.48,
  urls: [
   "audio/voice/9a7be7c3.mp3"
  ]
 },
 {
  key: "ae74033a",
  text: "Acid slime contact. Sticky, sour, final.",
  say: "Acid slime contact. Sticky, sour, final.",
  group: "Death · causes",
  seconds: 5.37,
  urls: [
   "audio/voice/ae74033a.mp3"
  ]
 },
 {
  key: "28442cb1",
  text: "You were blown apart.",
  say: "You were blown apart.",
  group: "Death · titles",
  seconds: 1.68,
  urls: [
   "audio/voice/28442cb1.mp3"
  ]
 },
 {
  key: "bb56a48b",
  text: "An explosive barrel fulfilled its destiny nearby.",
  say: "An explosive barrel fulfilled its destiny nearby.",
  group: "Death · causes",
  seconds: 3.42,
  urls: [
   "audio/voice/bb56a48b.mp3"
  ]
 },
 {
  key: "5693dc11",
  text: "Barrel chemistry: one, alchemist: zero.",
  say: "Barrel chemistry: one, alchemist: zero.",
  group: "Death · causes",
  seconds: 3.84,
  urls: [
   "audio/voice/5693dc11.mp3"
  ]
 },
 {
  key: "43a3a108",
  text: "You were taken.",
  say: "You were taken.",
  group: "Death · titles",
  seconds: 1.2,
  urls: [
   "audio/voice/43a3a108.mp3"
  ]
 },
 {
  key: "689bee0b",
  text: "A bat cashed in the smallest possible assassination.",
  say: "A bat cashed in the smallest possible assassination.",
  group: "Death · causes",
  seconds: 3.81,
  urls: [
   "audio/voice/689bee0b.mp3"
  ]
 },
 {
  key: "02e8d016",
  text: "Bitten out of the air by a flying nuisance.",
  say: "Bitten out of the air by a flying nuisance.",
  group: "Death · causes",
  seconds: 3.12,
  urls: [
   "audio/voice/02e8d016.mp3"
  ]
 },
 {
  key: "9b9e86d3",
  text: "A bomber slime chose mutual destruction. You were not consulted.",
  say: "A bomber slime chose mutual destruction. You were not consulted.",
  group: "Death · causes",
  seconds: 5.6,
  urls: [
   "audio/voice/9b9e86d3.mp3"
  ]
 },
 {
  key: "32b02cc3",
  text: "The fuse had one joke.",
  say: "The fuse had one joke.",
  group: "Death · causes",
  seconds: 2.32,
  urls: [
   "audio/voice/32b02cc3.mp3"
  ]
 },
 {
  key: "67f26592",
  text: "You burned.",
  say: "You burned.",
  group: "Death · titles",
  seconds: 0.82,
  urls: [
   "audio/voice/67f26592.mp3"
  ]
 },
 {
  key: "fa5e86f2",
  text: "Burned to death while still technically on fire.",
  say: "Burned to death while still technically on fire.",
  group: "Death · causes",
  seconds: 3.2,
  urls: [
   "audio/voice/fa5e86f2.mp3"
  ]
 },
 {
  key: "91830607",
  text: "Stopped, dropped, and forgot the rolling part.",
  say: "Stopped, dropped, and forgot the rolling part.",
  group: "Death · causes",
  seconds: 3.44,
  urls: [
   "audio/voice/91830607.mp3"
  ]
 },
 {
  key: "149140d7",
  text: "The Kiln died loudly and took you as a footnote.",
  say: "The Kiln died loudly and took you as a footnote.",
  group: "Death · causes",
  seconds: 4.39,
  urls: [
   "audio/voice/149140d7.mp3"
  ]
 },
 {
  key: "8bf5a6af",
  text: "Victory explosion. Timing could improve.",
  say: "[dryly] Victory explosion. Timing could improve.",
  group: "Death · causes",
  seconds: 3.66,
  urls: [
   "audio/voice/8bf5a6af.mp3"
  ]
 },
 {
  key: "6adc69ed",
  text: "The Kiln Colossus served you extra crispy.",
  say: "The Kiln Colossus served you extra crispy.",
  group: "Death · causes",
  seconds: 3.75,
  urls: [
   "audio/voice/6adc69ed.mp3"
  ]
 },
 {
  key: "834a9b53",
  text: "Molten rock, express delivery.",
  say: "Molten rock, express delivery.",
  group: "Death · causes",
  seconds: 2.72,
  urls: [
   "audio/voice/834a9b53.mp3"
  ]
 },
 {
  key: "722268d3",
  text: "You were crushed.",
  say: "You were crushed.",
  group: "Death · titles",
  seconds: 1.28,
  urls: [
   "audio/voice/722268d3.mp3"
  ]
 },
 {
  key: "ca7a90e2",
  text: "The Kiln Colossus stamped your ticket.",
  say: "The Kiln Colossus stamped your ticket.",
  group: "Death · causes",
  seconds: 2.59,
  urls: [
   "audio/voice/ca7a90e2.mp3"
  ]
 },
 {
  key: "8e281ebb",
  text: "A furnace with fists ended the expedition.",
  say: "A furnace with fists ended the expedition.",
  group: "Death · causes",
  seconds: 3.07,
  urls: [
   "audio/voice/8e281ebb.mp3"
  ]
 },
 {
  key: "de99388e",
  text: "The Kiln Colossus stamped, and the floor delivered it.",
  say: "The Kiln Colossus stamped, and the floor delivered it.",
  group: "Death · causes",
  seconds: 3.39,
  urls: [
   "audio/voice/de99388e.mp3"
  ]
 },
 {
  key: "1120618b",
  text: "Knocked flat by a shockwave you could have jumped.",
  say: "Knocked flat by a shockwave you could have jumped.",
  group: "Death · causes",
  seconds: 3.12,
  urls: [
   "audio/voice/1120618b.mp3"
  ]
 },
 {
  key: "4c6e719f",
  text: "The Kiln Colossus opened its vents. You were standing in the chimney.",
  say: "[dryly] The Kiln Colossus opened its vents. You were standing in the chimney.",
  group: "Death · causes",
  seconds: 4.8,
  urls: [
   "audio/voice/4c6e719f.mp3"
  ]
 },
 {
  key: "eb27caa7",
  text: "Roasted by a furnace letting off steam.",
  say: "Roasted by a furnace letting off steam.",
  group: "Death · causes",
  seconds: 2.8,
  urls: [
   "audio/voice/eb27caa7.mp3"
  ]
 },
 {
  key: "a2a070a7",
  text: "The current took you.",
  say: "The current took you.",
  group: "Death · titles",
  seconds: 1.36,
  urls: [
   "audio/voice/a2a070a7.mp3"
  ]
 },
 {
  key: "95f8ec08",
  text: "Electrocuted. The sparks were not applause.",
  say: "Electrocuted. The sparks were not applause.",
  group: "Death · causes",
  seconds: 4.28,
  urls: [
   "audio/voice/95f8ec08.mp3"
  ]
 },
 {
  key: "1ecc8201",
  text: "Conducted electricity better than good judgment.",
  say: "Conducted electricity better than good judgment.",
  group: "Death · causes",
  seconds: 3.68,
  urls: [
   "audio/voice/1ecc8201.mp3"
  ]
 },
 {
  key: "e5113309",
  text: "Exploded by local cave policy.",
  say: "Exploded by local cave policy.",
  group: "Death · causes",
  seconds: 2.78,
  urls: [
   "audio/voice/e5113309.mp3"
  ]
 },
 {
  key: "3ee85252",
  text: "A blast made a persuasive counterargument.",
  say: "A blast made a persuasive counterargument.",
  group: "Death · causes",
  seconds: 2.72,
  urls: [
   "audio/voice/3ee85252.mp3"
  ]
 },
 {
  key: "c3162e5f",
  text: "You were felled.",
  say: "You were felled.",
  group: "Death · titles",
  seconds: 1.28,
  urls: [
   "audio/voice/c3162e5f.mp3"
  ]
 },
 {
  key: "b0a8ad39",
  text: "A tree fell in the Works, and someone was around to hear it. Briefly.",
  say: "A tree fell in the Works, and someone was around to hear it. Briefly.",
  group: "Death · causes",
  seconds: 4.83,
  urls: [
   "audio/voice/b0a8ad39.mp3"
  ]
 },
 {
  key: "238fd6b4",
  text: "Timber. The creak was, in hindsight, the warning.",
  say: "[dryly] Timber. The creak was, in hindsight, the warning.",
  group: "Death · causes",
  seconds: 5.82,
  urls: [
   "audio/voice/238fd6b4.mp3"
  ]
 },
 {
  key: "47c8959e",
  text: "Cooked by open flame. The robe was not rated for this.",
  say: "Cooked by open flame. The robe was not rated for this.",
  group: "Death · causes",
  seconds: 4.24,
  urls: [
   "audio/voice/47c8959e.mp3"
  ]
 },
 {
  key: "f5efe778",
  text: "Fire solved the alchemist problem.",
  say: "Fire solved the alchemist problem.",
  group: "Death · causes",
  seconds: 2.56,
  urls: [
   "audio/voice/f5efe778.mp3"
  ]
 },
 {
  key: "3709450e",
  text: "You froze.",
  say: "You froze.",
  group: "Death · titles",
  seconds: 0.88,
  urls: [
   "audio/voice/3709450e.mp3"
  ]
 },
 {
  key: "5c4641dc",
  text: "Frozen stiff by a hostile frostbolt.",
  say: "Frozen stiff by a hostile frostbolt.",
  group: "Death · causes",
  seconds: 3.2,
  urls: [
   "audio/voice/5c4641dc.mp3"
  ]
 },
 {
  key: "a61d7e08",
  text: "Put on ice by something with aim.",
  say: "Put on ice by something with aim.",
  group: "Death · causes",
  seconds: 3.36,
  urls: [
   "audio/voice/a61d7e08.mp3"
  ]
 },
 {
  key: "ffd20377",
  text: "Rock, thrown by golem. Case closed.",
  say: "Rock, thrown by golem. Case closed.",
  group: "Death · causes",
  seconds: 3.54,
  urls: [
   "audio/voice/ffd20377.mp3"
  ]
 },
 {
  key: "75b4a9c6",
  text: "A golem skipped the warning and threw punctuation.",
  say: "A golem skipped the warning and threw punctuation.",
  group: "Death · causes",
  seconds: 3.76,
  urls: [
   "audio/voice/75b4a9c6.mp3"
  ]
 },
 {
  key: "6ddd62a9",
  text: "A golem explained gravity with its fists.",
  say: "A golem explained gravity with its fists.",
  group: "Death · causes",
  seconds: 2.72,
  urls: [
   "audio/voice/6ddd62a9.mp3"
  ]
 },
 {
  key: "79a825b5",
  text: "Flattened by stone with an opinion.",
  say: "Flattened by stone with an opinion.",
  group: "Death · causes",
  seconds: 2.64,
  urls: [
   "audio/voice/79a825b5.mp3"
  ]
 },
 {
  key: "c9cd4701",
  text: "Gunpowder remembered it was gunpowder.",
  say: "Gunpowder remembered it was gunpowder.",
  group: "Death · causes",
  seconds: 2.8,
  urls: [
   "audio/voice/c9cd4701.mp3"
  ]
 },
 {
  key: "b445fa69",
  text: "Powder line became a full stop.",
  say: "Powder line became a full stop.",
  group: "Death · causes",
  seconds: 2.08,
  urls: [
   "audio/voice/b445fa69.mp3"
  ]
 },
 {
  key: "b9f7c08a",
  text: "Hostile debris introduced itself at speed.",
  say: "Hostile debris introduced itself at speed.",
  group: "Death · causes",
  seconds: 3.44,
  urls: [
   "audio/voice/b9f7c08a.mp3"
  ]
 },
 {
  key: "29f45618",
  text: "Hit by cave mail, postage due.",
  say: "Hit by cave mail, postage due.",
  group: "Death · causes",
  seconds: 2.96,
  urls: [
   "audio/voice/29f45618.mp3"
  ]
 },
 {
  key: "79c416ad",
  text: "A hostile fireball delivered kiln-to-door service.",
  say: "A hostile fireball delivered kiln-to-door service.",
  group: "Death · causes",
  seconds: 4.24,
  urls: [
   "audio/voice/79c416ad.mp3"
  ]
 },
 {
  key: "137c9934",
  text: "Fireball to the face. Elegant? No. Effective? Yes.",
  say: "Fireball to the face. Elegant? No. Effective? Yes.",
  group: "Death · causes",
  seconds: 7.44,
  urls: [
   "audio/voice/137c9934.mp3"
  ]
 },
 {
  key: "2f3e7705",
  text: "You fell.",
  say: "You fell.",
  group: "Death · titles",
  seconds: 0.88,
  urls: [
   "audio/voice/2f3e7705.mp3"
  ]
 },
 {
  key: "16f819bf",
  text: "Killed by impact. The floor was technically uninvolved.",
  say: "Killed by impact. The floor was technically uninvolved.",
  group: "Death · causes",
  seconds: 3.76,
  urls: [
   "audio/voice/16f819bf.mp3"
  ]
 },
 {
  key: "dad3dc72",
  text: "Physics submitted the final blow.",
  say: "Physics submitted the final blow.",
  group: "Death · causes",
  seconds: 2.32,
  urls: [
   "audio/voice/dad3dc72.mp3"
  ]
 },
 {
  key: "f5c4bf47",
  text: "You melted.",
  say: "You melted.",
  group: "Death · titles",
  seconds: 1.04,
  urls: [
   "audio/voice/f5c4bf47.mp3"
  ]
 },
 {
  key: "f2dfbea6",
  text: "Lava bath. Zero stars, no refund.",
  say: "[dryly] Lava bath. Zero stars, no refund.",
  group: "Death · causes",
  seconds: 4.48,
  urls: [
   "audio/voice/f2dfbea6.mp3"
  ]
 },
 {
  key: "af8f3a57",
  text: "Attempted geology by immersion.",
  say: "Attempted geology by immersion.",
  group: "Death · causes",
  seconds: 2.85,
  urls: [
   "audio/voice/af8f3a57.mp3"
  ]
 },
 {
  key: "5952ac38",
  text: "You were drained.",
  say: "You were drained.",
  group: "Death · titles",
  seconds: 1.28,
  urls: [
   "audio/voice/5952ac38.mp3"
  ]
 },
 {
  key: "c5de5ef6",
  text: "Drained by leeches. Each one only had a small drink.",
  say: "Drained by leeches. Each one only had a small drink.",
  group: "Death · causes",
  seconds: 4.88,
  urls: [
   "audio/voice/c5de5ef6.mp3"
  ]
 },
 {
  key: "3ca3110e",
  text: "The Cisterns collected their toll, one sip at a time.",
  say: "The Cisterns collected their toll, one sip at a time.",
  group: "Death · causes",
  seconds: 4.18,
  urls: [
   "audio/voice/3ca3110e.mp3"
  ]
 },
 {
  key: "30486fc1",
  text: "The Leviathan surfaced for a snack.",
  say: "[dryly] The Leviathan surfaced for a snack.",
  group: "Death · causes",
  seconds: 3.19,
  urls: [
   "audio/voice/30486fc1.mp3"
  ]
 },
 {
  key: "f325bbf1",
  text: "Eaten by the problem in the pool.",
  say: "Eaten by the problem in the pool.",
  group: "Death · causes",
  seconds: 2.23,
  urls: [
   "audio/voice/f325bbf1.mp3"
  ]
 },
 {
  key: "3205a1d9",
  text: "The Leviathan brushed past and took most of you with it.",
  say: "The Leviathan brushed past and took most of you with it.",
  group: "Death · causes",
  seconds: 4.26,
  urls: [
   "audio/voice/3205a1d9.mp3"
  ]
 },
 {
  key: "ced1f053",
  text: "Grazed by a basement-sized appetite.",
  say: "Grazed by a basement-sized appetite.",
  group: "Death · causes",
  seconds: 3.28,
  urls: [
   "audio/voice/ced1f053.mp3"
  ]
 },
 {
  key: "e8071e34",
  text: "You were swept away.",
  say: "You were swept away.",
  group: "Death · titles",
  seconds: 1.76,
  urls: [
   "audio/voice/e8071e34.mp3"
  ]
 },
 {
  key: "f85bf22c",
  text: "The Leviathan slapped the pool at you, and the pool won.",
  say: "The Leviathan slapped the pool at you, and the pool won.",
  group: "Death · causes",
  seconds: 4.48,
  urls: [
   "audio/voice/f85bf22c.mp3"
  ]
 },
 {
  key: "f001ebff",
  text: "Tail-whipped by the plumbing.",
  say: "Tail-whipped by the plumbing.",
  group: "Death · causes",
  seconds: 2,
  urls: [
   "audio/voice/f001ebff.mp3"
  ]
 },
 {
  key: "e19779e7",
  text: "The Leviathan threw the pool at you.",
  say: "The Leviathan threw the pool at you.",
  group: "Death · causes",
  seconds: 2.64,
  urls: [
   "audio/voice/e19779e7.mp3"
  ]
 },
 {
  key: "b79860b2",
  text: "Defeated by high-velocity plumbing.",
  say: "Defeated by high-velocity plumbing.",
  group: "Death · causes",
  seconds: 2.83,
  urls: [
   "audio/voice/b79860b2.mp3"
  ]
 },
 {
  key: "a24c7037",
  text: "Struck down.",
  say: "Struck down.",
  group: "Death · titles",
  seconds: 1.28,
  urls: [
   "audio/voice/a24c7037.mp3"
  ]
 },
 {
  key: "78213380",
  text: "Self-administered lightning. Bold, brief.",
  say: "Self-administered lightning. Bold, brief.",
  group: "Death · causes",
  seconds: 4,
  urls: [
   "audio/voice/78213380.mp3"
  ]
 },
 {
  key: "ef6d4989",
  text: "Lightning found the shortest path through you.",
  say: "Lightning found the shortest path through you.",
  group: "Death · causes",
  seconds: 2.72,
  urls: [
   "audio/voice/ef6d4989.mp3"
  ]
 },
 {
  key: "469e5646",
  text: "Oiled, then lit. Classic wizard candle behavior.",
  say: "[dryly] Oiled, then lit. Classic wizard candle behavior.",
  group: "Death · causes",
  seconds: 4.96,
  urls: [
   "audio/voice/469e5646.mp3"
  ]
 },
 {
  key: "846d7bfa",
  text: "Turned into a lesson about accelerants.",
  say: "Turned into a lesson about accelerants.",
  group: "Death · causes",
  seconds: 2.88,
  urls: [
   "audio/voice/846d7bfa.mp3"
  ]
 },
 {
  key: "a24fe67f",
  text: "A Powder Mage made the cave throw things at you.",
  say: "A Powder Mage made the cave throw things at you.",
  group: "Death · causes",
  seconds: 3.35,
  urls: [
   "audio/voice/a24fe67f.mp3"
  ]
 },
 {
  key: "67b6d2a5",
  text: "Telekinetic debris: local, organic, fatal.",
  say: "Telekinetic debris: local, organic, fatal.",
  group: "Death · causes",
  seconds: 4.8,
  urls: [
   "audio/voice/67b6d2a5.mp3"
  ]
 },
 {
  key: "834b7a28",
  text: "A Rillback came out of the water with its mouth open.",
  say: "A Rillback came out of the water with its mouth open.",
  group: "Death · causes",
  seconds: 3.03,
  urls: [
   "audio/voice/834b7a28.mp3"
  ]
 },
 {
  key: "85fcb302",
  text: "The pool had teeth after all.",
  say: "The pool had teeth after all.",
  group: "Death · causes",
  seconds: 2.15,
  urls: [
   "audio/voice/85fcb302.mp3"
  ]
 },
 {
  key: "d992dcb1",
  text: "Flattened by a Rillback flailing on dry stone.",
  say: "Flattened by a Rillback flailing on dry stone.",
  group: "Death · causes",
  seconds: 3.84,
  urls: [
   "audio/voice/d992dcb1.mp3"
  ]
 },
 {
  key: "84b0b82c",
  text: "A stranded Rillback thrashed and you were in the way.",
  say: "A stranded Rillback thrashed and you were in the way.",
  group: "Death · causes",
  seconds: 4.08,
  urls: [
   "audio/voice/84b0b82c.mp3"
  ]
 },
 {
  key: "021173e9",
  text: "You were struck down.",
  say: "You were struck down.",
  group: "Death · titles",
  seconds: 1.95,
  urls: [
   "audio/voice/021173e9.mp3"
  ]
 },
 {
  key: "b4d1c838",
  text: "A Rootloper whipped its roots through you.",
  say: "A Rootloper whipped its roots through you.",
  group: "Death · causes",
  seconds: 3.08,
  urls: [
   "audio/voice/b4d1c838.mp3"
  ]
 },
 {
  key: "639f5bb5",
  text: "The undergrowth lashed back.",
  say: "The undergrowth lashed back.",
  group: "Death · causes",
  seconds: 1.92,
  urls: [
   "audio/voice/639f5bb5.mp3"
  ]
 },
 {
  key: "88d0dea0",
  text: "Self-inflicted explosion. The wand technically worked.",
  say: "Self-inflicted explosion. The wand technically worked.",
  group: "Death · causes",
  seconds: 4.96,
  urls: [
   "audio/voice/88d0dea0.mp3"
  ]
 },
 {
  key: "bd5b6740",
  text: "Own spell, own crater.",
  say: "Own spell, own crater.",
  group: "Death · causes",
  seconds: 2.4,
  urls: [
   "audio/voice/bd5b6740.mp3"
  ]
 },
 {
  key: "4db18cb0",
  text: "A slime bounced, bit, and somehow won.",
  say: "A slime bounced, bit, and somehow won.",
  group: "Death · causes",
  seconds: 3.2,
  urls: [
   "audio/voice/4db18cb0.mp3"
  ]
 },
 {
  key: "93ac4a43",
  text: "Slime contact: humiliating, but documented.",
  say: "[dryly] Slime contact: humiliating, but documented.",
  group: "Death · causes",
  seconds: 5.2,
  urls: [
   "audio/voice/93ac4a43.mp3"
  ]
 },
 {
  key: "a6931200",
  text: "A snapjaw closed on you. It had been waiting all day.",
  say: "A snapjaw closed on you. It had been waiting all day.",
  group: "Death · causes",
  seconds: 4.81,
  urls: [
   "audio/voice/a6931200.mp3"
  ]
 },
 {
  key: "9d0914d1",
  text: "Eaten by the shrubbery. The Rot Gardens are not decorative.",
  say: "[dryly] Eaten by the shrubbery. The Rot Gardens are not decorative.",
  group: "Death · causes",
  seconds: 5.28,
  urls: [
   "audio/voice/9d0914d1.mp3"
  ]
 },
 {
  key: "6e675487",
  text: "You succumbed.",
  say: "You succumbed.",
  group: "Death · titles",
  seconds: 1.28,
  urls: [
   "audio/voice/6e675487.mp3"
  ]
 },
 {
  key: "ee03f586",
  text: "A status effect finished the job quietly.",
  say: "A status effect finished the job quietly.",
  group: "Death · causes",
  seconds: 2.59,
  urls: [
   "audio/voice/ee03f586.mp3"
  ]
 },
 {
  key: "d8b31898",
  text: "The aftereffect got the last word.",
  say: "The aftereffect got the last word.",
  group: "Death · causes",
  seconds: 2.47,
  urls: [
   "audio/voice/d8b31898.mp3"
  ]
 },
 {
  key: "010ab859",
  text: "You were scalded.",
  say: "You were scalded.",
  group: "Death · titles",
  seconds: 1.46,
  urls: [
   "audio/voice/010ab859.mp3"
  ]
 },
 {
  key: "1687f393",
  text: "Scalded by a pressure vent. The gauge did warn you.",
  say: "Scalded by a pressure vent. The gauge did warn you.",
  group: "Death · causes",
  seconds: 4.4,
  urls: [
   "audio/voice/1687f393.mp3"
  ]
 },
 {
  key: "1ae676dc",
  text: "Steamed open by the works.",
  say: "Steamed open by the works.",
  group: "Death · causes",
  seconds: 2,
  urls: [
   "audio/voice/1ae676dc.mp3"
  ]
 },
 {
  key: "42e037b9",
  text: "The Stone Maw closed its jaw. The cave digests slowly.",
  say: "The Stone Maw closed its jaw. The cave digests slowly.",
  group: "Death · causes",
  seconds: 6.16,
  urls: [
   "audio/voice/42e037b9.mp3"
  ]
 },
 {
  key: "0dd7b5f3",
  text: "Swallowed by a mouth that looked like the floor.",
  say: "Swallowed by a mouth that looked like the floor.",
  group: "Death · causes",
  seconds: 3.2,
  urls: [
   "audio/voice/0dd7b5f3.mp3"
  ]
 },
 {
  key: "4b9d5a04",
  text: "You were poisoned.",
  say: "You were poisoned.",
  group: "Death · titles",
  seconds: 1.28,
  urls: [
   "audio/voice/4b9d5a04.mp3"
  ]
 },
 {
  key: "6ed85358",
  text: "Poison did the paperwork slowly.",
  say: "Poison did the paperwork slowly.",
  group: "Death · causes",
  seconds: 1.76,
  urls: [
   "audio/voice/6ed85358.mp3"
  ]
 },
 {
  key: "f6d7b040",
  text: "Toxic sludge won the debate.",
  say: "Toxic sludge won the debate.",
  group: "Death · causes",
  seconds: 2.32,
  urls: [
   "audio/voice/f6d7b040.mp3"
  ]
 },
 {
  key: "b64497dc",
  text: "You died.",
  say: "You died.",
  group: "Death · titles",
  seconds: 1.2,
  urls: [
   "audio/voice/b64497dc.mp3"
  ]
 },
 {
  key: "9ddb206f",
  text: "The caves decline to specify. Suspicious.",
  say: "The caves decline to specify. Suspicious.",
  group: "Death · causes",
  seconds: 4.56,
  urls: [
   "audio/voice/9ddb206f.mp3"
  ]
 },
 {
  key: "f58f9195",
  text: "Cause of death: alchemy happened.",
  say: "Cause of death: alchemy happened.",
  group: "Death · causes",
  seconds: 3.28,
  urls: [
   "audio/voice/f58f9195.mp3"
  ]
 },
 {
  key: "a9888d37",
  text: "The descent wrote the report in dust.",
  say: "The descent wrote the report in dust.",
  group: "Death · causes",
  seconds: 3.15,
  urls: [
   "audio/voice/a9888d37.mp3"
  ]
 },
 {
  key: "c03e88b4",
  text: "The Weaver got its revenge.",
  say: "The Weaver got its revenge.",
  group: "Death · causes",
  seconds: 2.43,
  urls: [
   "audio/voice/c03e88b4.mp3"
  ]
 },
 {
  key: "1967d415",
  text: "The Weaver filed you under caught.",
  say: "The Weaver filed you under caught.",
  group: "Death · causes",
  seconds: 2.93,
  urls: [
   "audio/voice/1967d415.mp3"
  ]
 },
 {
  key: "6a025a89",
  text: "The Weaver brought teeth. The web was optional.",
  say: "The Weaver brought teeth. The web was optional.",
  group: "Death · causes",
  seconds: 4.07,
  urls: [
   "audio/voice/6a025a89.mp3"
  ]
 },
 {
  key: "f2a19a95",
  text: "You were pinned.",
  say: "You were pinned.",
  group: "Death · titles",
  seconds: 1.36,
  urls: [
   "audio/voice/f2a19a95.mp3"
  ]
 },
 {
  key: "7abc81bf",
  text: "Pinned by the Weaver. No corkboard survived.",
  say: "Pinned by the Weaver. No corkboard survived.",
  group: "Death · causes",
  seconds: 4.24,
  urls: [
   "audio/voice/7abc81bf.mp3"
  ]
 },
 {
  key: "c3bc2233",
  text: "The Weaver threaded the needle through you.",
  say: "The Weaver threaded the needle through you.",
  group: "Death · causes",
  seconds: 2.4,
  urls: [
   "audio/voice/c3bc2233.mp3"
  ]
 },
 {
  key: "cfa9b63e",
  text: "Self-inflicted electrocution in water. Excellent conductivity, poor planning.",
  say: "Self-inflicted electrocution in water. Excellent conductivity, poor planning.",
  group: "Death · causes",
  seconds: 6.8,
  urls: [
   "audio/voice/cfa9b63e.mp3"
  ]
 },
 {
  key: "7772e8f7",
  text: "Wet, shocked, and briefly educational.",
  say: "Wet, shocked, and briefly educational.",
  group: "Death · causes",
  seconds: 3.84,
  urls: [
   "audio/voice/7772e8f7.mp3"
  ]
 },
 {
  key: "e106828c",
  text: "The Kiln is quiet.",
  say: "[softly] The Kiln is quiet.",
  group: "Ledger",
  seconds: 1.63,
  urls: [
   "audio/voice/e106828c.mp3",
   "audio/voice/e106828c-2.mp3"
  ]
 },
 {
  key: "b17079ec",
  text: "The Colossus is scrap, the Kiln is cooling, and somewhere a kettle is finally allowed to boil.",
  say: "[warmly] The Colossus is scrap, the Kiln is cooling, and somewhere a kettle is finally allowed to boil.",
  group: "Ledger",
  seconds: 7.76,
  urls: [
   "audio/voice/b17079ec.mp3",
   "audio/voice/b17079ec-2.mp3"
  ]
 },
 {
  key: "1380ece7",
  text: "You fell in the Bellows.",
  say: "You fell in the Bellows.",
  group: "Ledger",
  seconds: 1.98,
  urls: [
   "audio/voice/1380ece7.mp3"
  ]
 },
 {
  key: "611c3d75",
  text: "You left the Bellows early.",
  say: "You left the Bellows early.",
  group: "Ledger",
  seconds: 2.02,
  urls: [
   "audio/voice/611c3d75.mp3"
  ]
 },
 {
  key: "7204eb8a",
  text: "You fell in the Rot Gardens.",
  say: "You fell in the Rot Gardens.",
  group: "Ledger",
  seconds: 1.92,
  urls: [
   "audio/voice/7204eb8a.mp3"
  ]
 },
 {
  key: "344e1388",
  text: "You left the Rot Gardens early.",
  say: "You left the Rot Gardens early.",
  group: "Ledger",
  seconds: 2.16,
  urls: [
   "audio/voice/344e1388.mp3"
  ]
 },
 {
  key: "8b69f07b",
  text: "You fell in the Drowned Cisterns.",
  say: "You fell in the Drowned Cisterns.",
  group: "Ledger",
  seconds: 2.64,
  urls: [
   "audio/voice/8b69f07b.mp3"
  ]
 },
 {
  key: "1a038953",
  text: "You left the Drowned Cisterns early.",
  say: "You left the Drowned Cisterns early.",
  group: "Ledger",
  seconds: 2.64,
  urls: [
   "audio/voice/1a038953.mp3"
  ]
 },
 {
  key: "51bdf1b7",
  text: "You fell in the Kiln Heart.",
  say: "You fell in the Kiln Heart.",
  group: "Ledger",
  seconds: 1.92,
  urls: [
   "audio/voice/51bdf1b7.mp3"
  ]
 },
 {
  key: "0437bddb",
  text: "You left the Kiln Heart early.",
  say: "You left the Kiln Heart early.",
  group: "Ledger",
  seconds: 2.08,
  urls: [
   "audio/voice/0437bddb.mp3"
  ]
 },
 {
  key: "5a3bb28f",
  text: "Left the descent unharmed, which the Works will count as a draw.",
  say: "Left the descent unharmed, which the Works will count as a draw.",
  group: "Ledger",
  seconds: 5.12,
  urls: [
   "audio/voice/5a3bb28f.mp3"
  ]
 },
 {
  key: "46e1fe93",
  text: "Left the descent with the ledger open and the kettle still warm.",
  say: "Left the descent with the ledger open and the kettle still warm.",
  group: "Ledger",
  seconds: 3.31,
  urls: [
   "audio/voice/46e1fe93.mp3"
  ]
 },
 {
  key: "01a58998",
  text: "The Works decline to specify.",
  say: "The Works decline to specify.",
  group: "Ledger",
  seconds: 2.56,
  urls: [
   "audio/voice/01a58998.mp3"
  ]
 },
 {
  key: "ed0c2fec",
  text: "A new case on the rack: The Rime Case. Choose it at your next descent.",
  say: "A new case on the rack: The Rime Case. Choose it at your next descent.",
  group: "Kit unlocks",
  seconds: 6.63,
  urls: [
   "audio/voice/ed0c2fec.mp3"
  ]
 },
 {
  key: "3698d668",
  text: "A new case on the rack: The Ember Case. Choose it at your next descent.",
  say: "A new case on the rack: The Ember Case. Choose it at your next descent.",
  group: "Kit unlocks",
  seconds: 6.4,
  urls: [
   "audio/voice/3698d668.mp3"
  ]
 },
 {
  key: "6ac75f06",
  text: "A new case on the rack: The Storm Case. Choose it at your next descent.",
  say: "A new case on the rack: The Storm Case. Choose it at your next descent.",
  group: "Kit unlocks",
  seconds: 6.48,
  urls: [
   "audio/voice/6ac75f06.mp3"
  ]
 },
 {
  key: "eeda0140",
  text: "The material sandbox. Nothing here can hurt you, much.",
  say: "The material sandbox. Nothing here can hurt you, much.",
  group: "Workshop",
  seconds: 5.36,
  urls: [
   "audio/voice/eeda0140.mp3"
  ]
 }
];

/** The narrator candidates reading the same sample line. */
export const NARRATOR_CANDIDATES: readonly NarrationCandidate[] = [
 {
  id: "design-1",
  label: "Designed preview 1",
  url: "audio/voice/candidates/design-1.mp3"
 },
 {
  id: "design-2",
  label: "Designed preview 2",
  url: "audio/voice/candidates/design-2.mp3"
 },
 {
  id: "design-3",
  label: "Designed preview 3 (saved as the Docent)",
  url: "audio/voice/candidates/design-3.mp3"
 },
 {
  id: "daniel",
  label: "Daniel — the gruff old British wizard — full sample",
  url: "audio/voice/candidates/daniel.mp3"
 },
 {
  id: "docent",
  label: "The Docent (designed for Breathing Works) — full sample",
  url: "audio/voice/candidates/docent.mp3"
 },
 {
  id: "george",
  label: "George — Warm, Captivating Storyteller — full sample",
  url: "audio/voice/candidates/george.mp3"
 }
];
