// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Chat = __t.object("Chat", {
  id: __t.u64(),
  room: __t.string(),
  sender: __t.identity(),
  senderClientId: __t.string(),
  body: __t.string(),
  sentAt: __t.timestamp(),
});
export type Chat = __Infer<typeof Chat>;

export const Frame = __t.object("Frame", {
  room: __t.string(),
  senderClientId: __t.string(),
  senderConnection: __t.connectionId(),
  revision: __t.u64(),
  data: __t.string(),
});
export type Frame = __Infer<typeof Frame>;

export const Player = __t.object("Player", {
  connectionId: __t.connectionId(),
  identity: __t.identity(),
  room: __t.string(),
  clientId: __t.string(),
  role: __t.string(),
  build: __t.string(),
  joinedAt: __t.timestamp(),
});
export type Player = __Infer<typeof Player>;

export const Presence = __t.object("Presence", {
  connectionId: __t.connectionId(),
  room: __t.string(),
  worldKey: __t.string(),
  camX: __t.i32(),
  camY: __t.i32(),
  updatedAt: __t.timestamp(),
});
export type Presence = __Infer<typeof Presence>;

export const Session = __t.object("Session", {
  name: __t.string(),
  revision: __t.u64(),
  host: __t.option(__t.connectionId()),
  hostSince: __t.timestamp(),
  createdAt: __t.timestamp(),
});
export type Session = __Infer<typeof Session>;

